const categories = { 
  edible: "Speisesalze Salt", 
  lamps: "Salzlampen", 
  tiles: "Salzfliesen", 
  lick: "Lecksalze" 
} 
 
const data = [ 
  { 
    "category": "edible", 
    "desc": "Grobes pures pinkfarbenes Himalaya Salz ist unraffiniert und somit zu 100% naturrein. Himalaya Salz ist die  reinste Form von Salz und das Salz enthält Mineralien die für den menschlichen Körper  sehr wichtig sind. Pink gefärbtes Himalaya Salz hat seine Farbe durch den Eisengehalt. Das Vorkommen und die Abbau Methoden garantieren eine besonders hohe Reinheit. Da ist ein großer Unterschied zwischen Himalaya Salz und Meersalz. Himalaya Salz garantiert 100% Reinheit und das Meersalz ist durch Mikroplastik verunreinigt sowie durch Erdölreste und sonstige Verschmutzungen Umweltgifte. Dies allein ist ein Plädoyer wert und gute Argumente für Himalaya Salz zu sein da keinerlei Umweltgifte zu finden sind. Zudem hebt es sich durch die schöne Farbe von herkömmlichen Speisesalzen ab. Es ist sehr bekannt durch das erschienenen Buch 2001 “Wasser und Salz Urquell des Lebens”.Wasser und Salz ist lebensnotwendig für uns Menschen um zu existieren.Die lebensnotwendige Stellung des Salzes hängt von den Eigenschaften des Salzes ab.Es ist gut zum Würzen in der Küche man kann auch einen Beauty Tag einlegen denn es ist ein hervorragendes Badesalz. Wir bieten Himalaya Salz in zwei verschiedenen Farben an hellrosa und dunkelrosa. Das grobe pink Himalaya Salz ist zwischen 2-5 mm groß.",
    "name": "Grobes reines Pinkfarbenes Himalaya Salz", 
    "oldprice": "€3.50/kg", 
    "saleprice": "€2.79/kg", 
    "slug": "pink-salt", 
    "src": "../assets/img/portfolio/edible/ancient-ocean-himalayan-pink-salt-coarse-bowl.jpg", 
    "title": "Grobes Pinkfarbenes Himalaya Salz by Himalayan Salts" 
  }, 
  { 
    "category": "edible", 
    "desc": "Feines rosa Himalaya-Salz ist unraffiniert und daher 100% natürlich. Himalaya-Salz ist die reinste Form von Salz und enthält Mineralien, die für den menschlichen Körper sehr wichtig sind. Rosafarbenes Himalaya-Salz erhält seine Farbe durch den Eisengehalt. Das Vorkommen und die Abbaumethoden garantieren eine besonders hohe Reinheit. Dies ist der große Unterschied zwischen Himalaya-Salz und Meersalz. Himalaya-Salz garantiert eine 100-prozentige Reinheit und das Meersalz ist mit Mikroplastik sowie Umweltgiften aus Erdölrückständen und anderen Verschmutzungen belastet. Dies allein ist ein Plädoyer für Himalaya-Salz, da keine Umweltgifte zu finden sind. Außerdem hebt es sich durch seine schöne Farbe von herkömmlichen Speisesalzen ab. Es ist aus dem 2001 erschienenen Buch „Water & Salt: The Essence of Life“ bekannt. Wasser und Salz sind lebensnotwendig. Die lebenswichtige Stellung des Salzes hängt von den Eigenschaften des Salzes ab. Es ist gut, um die Küche zu würzen. Man kann auch einen Schönheitstag haben, denn es ist ein ausgezeichnetes Badesalz. Wir bieten Himalaya-Salz in zwei verschiedenen Farben an, hellrosa und dunkelrosa. Das feine rosa Himalayasalz ist zwischen 0,2-1 mm groß", 
    "name": "Feines rosa Salz", 
    "oldprice": "€ 3.60/kg ", 
    "saleprice": "€3.00/kg", 
    "slug": "fine-pink-salt", 
    "src": "../assets/img/portfolio/edible/ancient-ocean-himalayan-pink-salt-fine-bowl.jpg", 
    "title": "Fine Pink Salt by Himalayan Salts" 
  }, 
  { 
    "category": "edible", 
    "desc": "Granular Himalayan salt is unrefined and therefore 100% natural. Himalayan salt is the purest form of salt and contains minerals that are very important for the human body. Pink coloured Himalayan salt gets its colour from the iron content. The occurrence and the degradation methods guarantee a particularly high level of purity. This is the big difference between Himalayan salt and sea salt. Himalaya salt guarantees 100% purity, and the sea salt is contaminated with microplastics as well as environmental toxins from petroleum residues and other pollution. This alone is a plea in favour of Himalayan salt as there are no environmental toxins to be found. In addition, it stands out from conventional table salts thanks to its beautiful colour. It is well known from the published book 2001 “Water & Salt: The Essence of Life”. Water and salt are essential for our existence. The vital position of salt depends on the properties of the salt. It is good for flavouring the kitchen. One can also have a beauty day because it is an excellent bath salt. The granular pink Himalayan salt is between 1-4 mm in size", 
    "name": "Granular Pink Salt",  
    "oldprice": "€3.99/kg ", 
    "saleprice": "€3.55/kg ", 
    "slug": "granular-pink-salt",  
    "src": "../assets/img/portfolio/edible/ancient-ocean-himalayan-pink-salt-small-bowl.jpg", 
    "title": "Granular Salt by Himalayan Salts" 
  }, 
  { 
    "category": "edible", 
    "desc": "Im Moment nicht verfügbar", 
    "name": "Jodiertes Salz",  
    "oldprice": "€3.50/kg ", 
    "saleprice": "€3.00/kg ", 
    "slug": "iodized-salt",  
    "src": "../assets/img/portfolio/edible/iodized-salt-fine-bowl.jpg", 
    "title": "Jodiertes Salz by Himalayan Salts" 
  }, 
  { 
    "category": "edible", 
    "desc": "Himalaya Schwarzsalz ist auch genannt  Black salt, Kala Namak(in Urdu Sprache) und Kala Loon (in Punjabi Sprache). Es läuft unter der ayurvedischen Nahrungsmittelkette und ist gesundheitsfördernd auch in der veganen Küche wird es gerne verwendet. Das Schwarzsalz kommt aus Indien/Pakistan, es besteht aus 98% aus Natriumchlorid und hat noch mehrere Mineralienanteile zu bieten die sehr wichtig für den menschlichen Körper sind. Das Schwarzsalz ist blutdrucksenkend und für eine salzarme Ernährung zu empfehlen. Speisen mit Früchten haben durch das Würzen des Schwarzsalzes einen abgerundeten Geschmack.In der indischen Medizin hat es einen guten Stellenwert. Es wird in heißen Ländern besonders für Getränke verwendet, da es eine isotonische Wirkung hat. Für Sportler ist es  geeignet und zu empfehlen und für Menschen mit großen Aktivitäten um den Mineralhaushalt abzudecken. Probleme mit Sodbrennen lassen sich gut einstellen.", 
    "name": "Himalaya Schwarz Salz",  
    "oldprice": "€9.00/500g", 
    "saleprice": "€7.5/500g ", 
    "slug": "black-salt",  
    "src": "../assets/img/portfolio/edible/kala-namak-indian-black-salt.jpg",  
    "title": "Himalaya Schwarz Salz by Himalayan Salts" 
  }, 
  { 
    "category": "edible", 
    "desc": "Im Moment nicht verfügbar", 
    "name": "Australisches Meersalz",  
    "oldprice": "€20.00/500g", 
    "saleprice": "€19.00/500g", 
    "slug": "australian-sea-salt",  
    "src": "../assets/img/portfolio/edible/paragon-australian-sea-salt-fine-bowl.jpg",  
    "title": "Australisches Meersalz by Himalayan Salts" 
  }, 
  { 
    "category": "edible", 
    "desc": "Im Moment nicht verfügbar", 
    "name": "Ozeansalz",  
    "oldprice": "€20.00", 
    "saleprice": "€18.00", 
    "slug": "ocean-salt",  
    "src": "../assets/img/portfolio/edible/pure-ocean-premium-sea-salt-fine-bulk-bowl.jpg",  
    "title": "Ozeansalz by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Engelszeichen gibt Ihnen das Gefühl von Vertrauen, Schutz und Segen in Ihrem Leben. Die Lampe sieht toll aus und vermittelt das Bild von Schutz, Spiritualität und bereichert die Heilkräfte des Salzes. Diese Schwingungsschwingungen an deiner Seite helfen dir, deine Lebensaufgabe zu erfüllen. Inklusive 1 Glühbirne, 1 m Kabel mit Fassung und Holzsockel.", 
    "name": "Engel Salzlampe",  
    "saleprice": "30.99 €", 
    "oldprice": "35.00 €", 
    "slug": "angel-salt-lamp",  
    "size": "20x15x7cm", 
    "weight": "2.5-3 kg", 
    "src": "../assets/img/portfolio/lamps/angel.png",  
    "title": "Engel Salzlampe by Himalayan Salts" 

  }, 
  { 
    "category": "lamps", 
    "desc": "Die Lampe das Boot vermittelt eine wunderbare gesunde Raumatmosphäre und ein sehr gutes Raumklima.Es erinnert an Sehnsucht, Freizeit und Urlaub.", 
    "name": "Boot Salz Lampe",  
    "saleprice": "37.99 €", 
    "oldprice": "39.99 €", 
    "slug": "boat-salt-lamp",  
    "size": "15x15cm", 
    "weight": "2.5-3 kg", 
    "src": "../assets/img/portfolio/lamps/boat.png",  
    "title": "Boot Salz Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die Schüssel Lampe strahlt eine wunderschöne Atmosphäre aus. Gibt ein gesundes Raumklima und lädt zum Relaxen und Erholen ein.", 
    "name": "Schüssel Salz Lampe",  
    "saleprice": "22.99 €", 
    "oldprice": "25.00 €", 
    "slug": "bowl-salt-lamp",  
    "size": "15x15 cm", 
    "weight": "2-2.5 kg", 
    "src": "../assets/img/portfolio/lamps/bowl.png",  
    "title": "Schüssel Salz Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die Feuerschüssel Lampe verleiht jedem Raum eine ganz besondere  Atmosphäre.Salzkristall Lampe strahlt nicht nur warmes Licht aus sondern hat auch positive Eigenschaften fördert die Gesundheit.Sie verbessert das Raumklima und lädt zum Entspannen ein.", 
    "name": "Feuerschüssel Lampe",  
    "saleprice": "30.99 €", 
    "oldprice": "35.00 €", 
    "slug": "bowl-2-salt-lamp",  
    "size": "15x10x15 cm", 
    "weight": "3-3.5 kg", 
    "src": "../assets/img/portfolio/lamps/bowl-2.jpg",  
    "title": "Feuerschüssel Lampe by Himalayan Salts" 

  }, 
  { 
    "category": "lamps", 
    "desc": "Kugelförmiges Salz kann im Raum der Jäger oder Soldaten installiert werden, die Waffen und Kugeln lieben. Es ist eher ein maßgeschneidertes Kunstwerk.", 
    "name": "Kugelhalter Candle Holder",  
    "saleprice": "4.89 €", 
    "oldprice": "5.00 €", 
    "slug": "bullet-salt-lamp",  
    "size": "8-10 cm", 
    "weight": "1 kg", 
    "src": "../assets/img/portfolio/lamps/bullet.png",   
    "title": "Kugelhalter Salt Lamp by Himalayan Salts" 

  }, 
  { 
    "category": "lamps", 
    "desc": "Die Kaktus Lampe verzaubert ihren Raum,sie schafft eine bessere Atmosphäre durch ein gesünderes Raumklima.Hilft beim Beseitigen von Rauch und anderen schädlichen Stoffen und mindert Allergien. Sie hat ein wärmendes Licht und der Raum wird zu einer Wohlfühloase.", 
    "name": "Kaktus Salz Lampe",  
    "saleprice": "30.99 €", 
    "oldprice": "35.00 €", 
    "slug": "cactus-salt-lamp",  
    "size": "15-20 cm", 
    "weight": "2.5-3 kg", 
    "src": "../assets/img/portfolio/lamps/cactus.png",   
    "title": "Kaktus Salz Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Der Höhlenhalter ist einzigartig und strahlt Wärme und Geborgenheit aus.Er verbessert das Raumklima, das Atmen wird erleichtert und Allergene werden vermindert.Lässt  entspannen,ausruhen und sich wohlfühlen.", 
    "name": "Höhlenkerzen Halter",  
    "saleprice": "18.99 €", 
    "oldprice": "20.00 €", 
    "slug": "cave-salt-lamp",  
    "size": "10x11x13 cm", 
    "weight": "1.5-2 kg", 
    "src": "../assets/img/portfolio/lamps/cave.png",   
    "title": "Höhlenkerzen Halter by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die Salzlampe des Weihnachtsbaums lässt uns an Weihnachten denken.Es ist speziell ein Winterprodukt,das sowohl von Erwachsenen als auch von Kindern geliebt wird.Die Lampe verbessert das Raumklima und weckt Gefühle wie bei einem Spaziergang im Wald.Das gemütliche Licht lädt zum Entspannen ein.Danach fühlt man sich wie nach einer heilenden Therapie.", 
    "name": "Weihnachtsbaums Salz Lampe",  
    "saleprice": "28.99 €", 
    "oldprice": "30.00 €", 
    "slug": "christmas-tree-salt-lamp",  
    "size": "17-20 cm", 
    "weight": "2-2.5 kg", 
    "src": "../assets/img/portfolio/lamps/christmas-tree.png",   
    "title": "Weihnachtsbaums Salz Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Das Kreuz ist das Symbol des Christentums, es sorgt dafür das Pech fernzuhalten und den Körper sowie auch die Seele zu reinigen,Das Kreuz steht für Liebe,Frieden,Gerechtigkeit und Vergebung.Die Salzlampe verbessert das Raumklima sorgt für ein angenehmes Licht und ein Gefühl der Sicherheit.", 
    "name": "Kreuz Salz Lampe",  
    "saleprice": "40.99 €", 
    "oldprice": "45.00 €", 
    "slug": "cross-salt-lamp",  
    "size": "25x25x10 cm", 
    "weight": "2-2.5 kg", 
    "src": "../assets/img/portfolio/lamps/cross.png",   
    "title": "Kreuz Salz Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die kubische Salzlampe beeindruckt mit ihrer Form.Sie verbessert das Raumklima.Vermittelt eine tolle Atmosphäre zum Wohlfühlen.Die kubische Lampe schmückt nicht nur den Raum mit ihrem Licht, sondern zieht auch die Aufmerksamkeit der Besucher auf sich.", 
    "name": "Kubische Salz Lampe",  
    "saleprice": "50.99 €", 
    "oldprice": "60.00 €", 
    "slug": "cubical-salt-lamp",  
    "size": "20x20x24 cm", 
    "weight": "4.5-6 kg", 
    "src": "../assets/img/portfolio/lamps/cubical-1.jpg",   
    "title": "Kubische Salz Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die fein polierte kubische Lampe ist ein Hingucker und verleiht einen hypnotisierenden Look. Die kubische Salzlampe besticht durch ihre Form. Es verbessert das Raumklima, schafft eine tolle Atmosphäre zum Entspannen und Wohlfühlen. Die kubische Leuchte schmückt mit ihrem Licht nicht nur den Raum, sondern zieht auch die Aufmerksamkeit der Besucher auf sich. Inklusive 1 Glühbirne, 1 m Kabel mit Fassung und Holzsockel.", 
    "name": "Kubische Salzlampe",  
    "saleprice": "27.99 €", 
    "oldprice": "28.99 €", 
    "slug": "cubical-2-salt-lamp",  
    "size": "10x10x12 cm", 
    "weight": "2-2.5 kg", 
    "src": "../assets/img/portfolio/lamps/cubical-2.png",   
    "title": "Kubische Salzlampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die kubische Lampe mit Karos hat ein auffälliges und innovatives Design.Sie sieht nicht nur faszinierend aus und beeindruckt jeden mit ihrer Form.Sie verbessert das Raumklima.Schafft  auch eine großartige Atmosphäre zum Entspannen und Wohlfühlen.Es ist eines der beliebtesten Produkte der Kunden.", 
    "name": "Karo kubische Salz Lampe",  
    "saleprice": "55.99 €", 
    "oldprice": "65.00 €", 
    "slug": "cubical-3-salt-lamp",  
    "size": "20x20x24 cm", 
    "weight": "4.5-6 kg", 
    "src": "../assets/img/portfolio/lamps/cubical-3.png",   
    "title": "Karo kubische Salz Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die zylindrische Salzlampe verbessert die Raumluft sorgt für Wohlfühlatmosphäre und das warme Licht sorgt für Geborgenheit.Auch wird die Raumluft verbessert,das Atmen erleichtert.", 
    "name": "Zylindrische Salz Lampe",  
    "saleprice": "24.99 €", 
    "oldprice": "30.00 €", 
    "slug": "cylinderical-salt-lamp",  
    "size": "16x10 cm", 
    "weight": "2-2.5 kg", 
    "src": "../assets/img/portfolio/lamps/cylinder.png",   
    "title": "Zylindrische Salz Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die Salzkristall Lampe hat die Form einer Rose.Sie beeindruckt durch  ihr Design.Sie überflutet den Raum mit ihrem wärmenden  orangefarbenen Licht. Schafft ein gutes Raumklima verbessert die Energie sorgt für Entspannung und baut Stress ab.", 
    "name": "Floral Lampe",  
    "saleprice": "35.99 €", 
    "oldprice": "40.00 €", 
    "slug": "date-salt-lamp",  
    "size": "15x15x10 cm", 
    "weight": "2-2.5 kg", 
    "src": "../assets/img/portfolio/lamps/date.png",   
    "title": "Floral Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Der Kerzen Diamant gibt ein behagliches Licht ab.Sie strahlt wie ein geschliffener Diamant.Die Kerze sorgt für eine Wohlfühlatmosphäre,eine gute Raumluft.Das wärmende Licht erhellt die Seele und sorgt für Entspannung und Geborgenheit. Die Kerze beeindruckt durch ihre einzigartige und geometrische Form.", 
    "name": "Diamanten Salz Kerze",  
    "saleprice": "17.99 €", 
    "oldprice": "23.00 €", 
    "slug": "diamond-salt-lamp",  
    "size": "15x12x12 cm", 
    "weight": "2.5-3 kg", 
    "src": "../assets/img/portfolio/lamps/diamond.png",   
    "title": "Diamanten Salz Kerze by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Der Diamant unter den Salzlampe ist dieses Produkt.DasLicht der Lampe strahlt hell  und sehr intensiv.Die Raumluft wird verbessert.Man spürt diese wunderbare Atmosphäre. Sie lässt Ruhe und Geborgenheit in diesen Raum fließen.Vermittelt Sicherheit und sorgt für eine positive Stimmung.", 
    "name": "Diamanten Salz Lampe",  
    "saleprice": "24.99 €", 
    "oldprice": "27.00 €", 
    "slug": "diamond-2-salt-lamp",  
    "size": "15x12x12 cm", 
    "weight": "2.5-3 kg", 
    "src": "../assets/img/portfolio/lamps/dimaond-2.png",   
    "title": "Diamanten Salz Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Eine Dollar Lampe immer zu Hause zu haben symbolisiert! Keine NOT und immer Brot. Dieses kleine Kunstwerk inspiriert durch seine Form.Sorgt für eine gute Raumluft und eine schöne Atmosphäre.", 
    "name": "Dollar Salz Lampe",  
    "saleprice": "12.99 €", 
    "oldprice": "15.00 €", 
    "slug": "dollar-salt-lamp",  
    "size": "10x10x7 cm", 
    "weight": "2.5-3 kg", 
    "src": "../assets/img/portfolio/lamps/dollar.png",   
    "title": "Dollar Salz Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Der Trommel Kerzenhalter ist innovativ und verleiht dem Musikliebhaber die gewünschte Atmosphäre.Sorgt für eine gute Raumluft für Entspannung, Geborgenheit und Zufriedenheit.Der Trommel Salz Kerzenhalter ist ein Blickfang für jeden.Schaffen sie Platz für einen Trommel Kerzenhalter.", 
    "name": "Trommel Salz",  
    "saleprice": "20.99 €", 
    "oldprice": "25.00 €", 
    "slug": "drum-salt-lamp",  
    "size": "15x15x15 cm", 
    "weight": "1-1.5 kg", 
    "src": "../assets/img/portfolio/lamps/drum.png",   
    "title": "Trommel Salz by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Diese Lampe ist Zeichen von Leben und Vielfalt sie sorgt für gute Raumluft,eine wunderbare Atmosphäre. Die Lampe vermittelt das Gefühl der Geborgenheit sorgt für Entspannung.Durch ihre entzückende Form lässt sie sich gut verkaufen.", 
    "name": "Ei Salz Lampe",  
    "saleprice": "30.99 €", 
    "oldprice": "35.00 €", 
    "slug": "egg-salt-lamp",  
    "size": "15x15 cm", 
    "weight": "2.5-3.5 kg", 
    "src": "../assets/img/portfolio/lamps/egg.png",   
    "title": "Ei Salz Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Der Augen Kerzenhalter beeindruckt mit seinem Design.Er verbessert das Raumklima..Man entspannt sich bei der guten Atmosphäre.", 
    "name": "Augen Kerzenhalter",  
    "saleprice": "9.99 €", 
    "oldprice": "13.00 €", 
    "slug": "eye-salt-lamp",  
    "size": "13x8x5 cm", 
    "weight": "1-1.5 kg", 
    "src": "../assets/img/portfolio/lamps/eye.png",   
    "title": "Augen Kerzenhalter by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die Feuer Salzlampe vermittelt das Bild von brennendem Feuer und Kohle.Sie bringt Entspannung und zaubert Wärme und Komfort in den Raum.Das Raumklima wirkt sich positiv auf Ihre Gesundheit aus.Es lässt durchatmen und entspannen.", 
    "name": "Feuer Salz Lampe",  
    "saleprice": "30.99 €", 
    "oldprice": "35.00 €", 
    "slug": "fire-bowl-salt-lamp",  
    "size": "15x10x10 cm", 
    "weight": "3-3.5 kg", 
    "src": "../assets/img/portfolio/lamps/fire-bowl.png",   
    "title": "Feuer Salz Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Es gibt das Bild einer Flamme und vermittelt das Gefühl von Frische und Wärme. Die Salzkerzenlampe sorgt für ein gutes Raumklima und wirkt entspannend. Das warme orange Licht der Lampe ist ermutigend und entspannend. Salz zieht Feuchtigkeit an und nimmt Feuchtigkeit auf. Das rot-orange Lichtspektrum hilft Stress abzubauen.", 
    "name": "Flammensalzlampe",  
    "saleprice": "10.99 €", 
    "oldprice": "12.00 €", 
    "slug": "flame-salt-lamp",  
    "size": "10x8 cm", 
    "weight": "1 kg", 
    "src": "../assets/img/portfolio/lamps/flame.png",   
    "title": "Flammensalzlampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die Blumen Kristallsalz Lampe schafft eine florale Atmosphäre mit warmen Lichtspektrum.Die Lampe verbessert das  Raumklima und vermittelt das Gefühl von Frische und Wärme.Sie lädt zum Träumen ein und man fühlt sich wie im Garten.", 
    "name": "Blumen Kristallsalz Lampe",  
    "saleprice": "10.99 €", 
    "oldprice": "15.00 €", 
    "slug": "flower-salt-lamp",  
    "size": "10x10x10 cm", 
    "weight": "1-1.5 kg", 
    "src": "../assets/img/portfolio/lamps/flower.png",   
    "title": "Blumen Kristallsalz Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die Salzkristalllampe hat die Form einer Rose. Es besticht durch sein Design. Wenn es mit seinem orangefarbenen Licht erstrahlt, schafft es ein gutes Raumklima, verbessert die Energie, sorgt für Entspannung, reduziert Schlafstörungen und baut Stress ab. Die Blumenkristall-Salzlampe schafft eine florale Atmosphäre mit einem warmen Lichtspektrum. Inklusive 1 Glühbirne, 1 m Kabel mit Fassung und Holzsockel.", 
    "name": "Blumensalzlampe",  
    "saleprice": "33.99 €", 
    "oldprice": "36.00 €", 
    "slug": "flower-2-salt-lamp",  
    "size": "20x15 cm", 
    "weight": "3-3.5 kg", 
    "src": "../assets/img/portfolio/lamps/flower-2.png",   
    "title": "Blumensalzlampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die Schloss Salzkristalllampe beeindruckt mit ihrem Design.Sie ist  gedacht fürs mutige Menschen.Die Lampe vermittelt Stärke und ist frei von Umweltgiften.Sie verbessert das Raumklima und sorgt für eine positive Atmosphäre.", 
    "name": "Schloss Salzkristall Lampe",  
    "saleprice": "40.99 €", 
    "oldprice": "45.00 €", 
    "slug": "fort-salt-lamp",  
    "size": "20-25 cm", 
    "weight": "3-3.5 kg", 
    "src": "../assets/img/portfolio/lamps/fort.png",   
    "title": "Schloss Salzkristall Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die Salzwelt Kristall Lampe beeindruckt mit ihrem Design.Ihr gelb orangefarbenen Licht setzt positive Energie frei.Die Lampe verbessert das Raumklima,sorgt für Entspannung und Wohlfühlatmosphäre.Es ist ein  beliebtes Produkt von Kunden.", 
    "name": "Welt Salzkristall Lampe",  
    "saleprice": "35.99 €", 
    "oldprice": "40.00 €", 
    "slug": "globe-salt-lamp",  
    "size": "15x15 cm", 
    "weight": "2.5-3 kg", 
    "src": "../assets/img/portfolio/lamps/globe-1.jpg",   
    "title": "Welt Salzkristall Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Bei dieser Lampe handelt es sich um ein tolles Naturprodukt denn der Salzkristall stammt vom Himalaya,für seine gesundheitsfördernde Wirkung ist der Salzkristall bekannt,außerdem soll er für Harmonie und inneres Gleichgewicht sorgen.Er verbessert das Raumklima und sorgt für eine positive Atmosphäre.", 
    "name": "Salzkristall Lampe",  
    "saleprice": "30.99 €", 
    "oldprice": "35.00 €", 
    "slug": "globe-2-salt-lamp",  
    "size": "15x15 cm", 
    "weight": "2.5-3 kg", 
    "src": "../assets/img/portfolio/lamps/globe-2.png",   
    "title": "Salzkristall Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Dieser Kerzenhalter eignet sich hervorragend für ein Candle Light Dinner.Die Kerze schafft eine hervorragende Atmosphäre,positive Energie,verbindet Herzen zu Herzen,sendet Wärme und Funken.Sie ist ein Sinnbild der Liebe,die Kerze verbessert das Raumklima lässt entspannen,fördert die Leichtigkeit und das Glücklichseins.", 
    "name": "Herz Kerzenhalter",  
    "saleprice": "9.99 €", 
    "oldprice": "11.00 €", 
    "slug": "heart-salt-lamp",  
    "size": "10x10 cm", 
    "weight": "1 kg", 
    "src": "../assets/img/portfolio/lamps/heart.png",   
    "title": "Herz Kerzenhalter by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die Herz Salzkristallen spricht für Romantik und Liebe.Sie steht für Vertrauen und Zuneigung.Sie verbessert das Raumklima schafft ein harmonische Atmosphäre und ist eine tolle Dekoration für jeden Raum.", 
    "name": "Herz Salz Lampe",  
    "saleprice": "42.99 €", 
    "oldprice": "45.00 €", 
    "slug": "heart-2-salt-lamp",  
    "size": "10x17x17 cm", 
    "weight": "3-3.5 kg", 
    "src": "../assets/img/portfolio/lamps/heart-2.png",   
    "title": "Herz Salz Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Der Kerzenblatthalter mit Kerze wirft ein warmes behagliches Licht in den Raum. Es verführt  zum Relaxen, fördert das Wohlbefinden, verbessert das Raumklima, sorgt für positive Energie. Schafft eine gute Atmosphäre", 
    "name": "Kerzen Blatt Halter",  
    "saleprice": "34.99 €", 
    "oldprice": "40.00 €", 
    "slug": "leaf-salt-lamp",  
    "size": "15x20 cm", 
    "weight": "2.5-3 kg", 
    "src": "../assets/img/portfolio/lamps/leaf.png", 
    "title": "Kerzen Blatt Halter by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die Blattsalzkristalllampe beeindruckt durch ihr Design.Sie fördert die Gesundheit, verbessert das Raumklima und schafft positive Energie. Die Lampe dient zum Entspannen, baut Stress ab und sorgt für Wohlbefinden.Das Blattdesign ist ansprechend und Stilecht.", 
    "name": "Blatt Salzkristall Lampe",  
    "saleprice": "17.99 €", 
    "oldprice": "20.00 €", 
    "slug": "leaf-2-salt-lamp",  
    "size": "10x12 cm", 
    "weight": "1 kg", 
    "src": "../assets/img/portfolio/lamps/leaf-2.png",   
    "title": "Blatt Salzkristall Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die Lotus Salzkristalllampe beeindruckt durch ihre Form. Das Symbol bedeutet Reinigung des Gewissens. Der Lotus steht für Weisheit und Wissen.Symbol für Selbsterkenntnis. Die Lotusblume ist eine Wachstums Blume und führt zur Erleuchtung. Mit der Lotusblüte verbindet man auch Herzlichkeit und Leidenschaft. Die Lampe schafft ein gutes Raumklima und sorgt für eine positive Energie.", 
    "name": "Lotus Salz Lampe",  
    "saleprice": "33.99 €", 
    "oldprice": "36.00 €", 
    "slug": "lotus-salt-lamp",  
    "size": "20x15 cm", 
    "weight": "3-3.5 kg", 
    "src": "../assets/img/portfolio/lamps/lotus.png",   
    "title": "Lotus Salz Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die Pilzsalzkristalllampe zeichnet sich durch ihre Form aus. Es ist ein Naturprodukt. Die Salzlampe ist frei von Umweltgiften. Der Salzkristall verbessert die Atemluft, schafft ein gutes Raumklima, lässt Sie sich entspannen und wohlfühlen. Pilzliebhaber! Hier ist ein weiteres maßgeschneidertes Ausstellungsstück für Sie, das Ihnen ein Lächeln und einen strahlenden Tag verleiht. Inklusive 1 Glühbirne, 1 m Kabel mit Fassung und Holzsockel.", 
    "name": "Pilzsalzlampe",  
    "saleprice": "35.99 €", 
    "oldprice": "40.00 €", 
    "slug": "mushroom-salt-lamp",  
    "size": "20x15x10 cm", 
    "weight": "2.5-3 kg", 
    "src": "../assets/img/portfolio/lamps/mushroom.png",   
    "title": "Pilzsalzlampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die Salzkristalllampe mit vier Kerzen besticht durch ihre natürliche Form. Sie spendet ein warmes, angenehmes Licht, erzeugt positive Energie und eine gute Atmosphäre. Die Leuchte reinigt die Raumluft, sorgt für Entspannung und schafft Wohlbefinden.", 
    "name": "Natürliche Salzlampe",  
    "saleprice": "13.99 €", 
    "oldprice": "15.00 €", 
    "slug": "4 Candles salt lamp",  
    "size": "15x10 cm", 
    "weight": "2-2.5 kg", 
    "src": "../assets/img/portfolio/lamps/natural-1.png",   
    "title": "Natürliche Salzlampe by Himalayan Salts"  
  }, 
  { 
    "category": "lamps", 
    "desc": "Die Oktan Salzkristall Lampe beeindruckt durch ihre Form. Die Lampe steht für helle Flüssigkeit, der Raum wird hell durchflutet und trotzdem ist das Licht behaglich und warm. Der Salzkristall sorgt für positive Energie, eine rundum gute Atmosphäre verbessert das Raumklima und baut Stress ab.", 
    "name": "Oktan Salzkristall Lampe",  
    "saleprice": "30.99 €", 
    "oldprice": "35.00 €", 
    "slug": "octane-salt-lamp",  
    "size": "15x20 cm", 
    "weight": "2.5-3 kg", 
    "src": "../assets/img/portfolio/lamps/octacone.png",   
    "title": "Oktan Salzkristall Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die Orchidee Salzkristalllampe beeindruckt durch ihre einzigartige Form. Sie steht für Schönheit, Einzigartigkeit, Leidenschaft, Liebe, Sehnsucht und Fruchtbarkeit. Die Lampe verbessert das Raumklima, fördert eine gesunde positive Atmosphäre, sorgt für Entspannung und Wohlbefinden.Diese Lampe wird gerne von liebenden Paaren gekauft.", 
    "name": "Orchidee Salzkristall Lampe",  
    "saleprice": "31.99 €", 
    "oldprice": "35.00 €", 
    "slug": "orchid-salt-lamp",  
    "size": "10x10x20 cm", 
    "weight": "2.5-3 kg", 
    "src": "../assets/img/portfolio/lamps/orchid.png",   
    "title": "Orchidee Salzkristall Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die ovale Salzkristalllampe beeindruckt durch ihre einzigartige Form. Die Lampe symbolisiert einen dreidimensionalen Körper den wir als Ovoid bezeichnen. Der Salzkristall durchflutet den Raum durch sein einzigartiges orangerotfarbenes Licht und verwandelt ihn in eine Wohlfühloase.  Die Salzlampe fördert die Gesundheit schafft gute Raumluft, eine positive behagliche Atmosphäre, bringt Entspannung und dient zum Stressabbau.", 
    "name": "Ovale Salzkristall Lampe",  
    "saleprice": "29.99 €", 
    "oldprice": "32.99 €", 
    "slug": "oval-salt-lamp",  
    "size": "15x15x20 cm", 
    "weight": "3.5-5 kg", 
    "src": "../assets/img/portfolio/lamps/oval.jpg",   
    "title": "Ovale Salzkristall Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die Salzkristalllampe beeindruckt durch ihre einzigartige Form. Sie dient als Symbol des Christentum z.b. Palmsonntag und im lateinischen bedeutet das  Handfläche.Das Salz ist ein Naturprodukt verbessert das Raumklima sorgt für eine wunderbare Atmosphäre dient der Entspannung und sorgt für Wohlbefinden.", 
    "name": "Palm Salzkristall Lampe",  
    "saleprice": "35.99 €", 
    "oldprice": "40.00 €", 
    "slug": "palm-salt-lamp",  
    "size": "20x15x10 cm", 
    "weight": "2.5-3 kg", 
    "src": "../assets/img/portfolio/lamps/palm.png",   
    "title": "Palm Salzkristall Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die Pyramide Salzkristalllampe beeindruckt durch ihre Form.Sie erhellt den Raum mit ihrem wärmenden Licht.Die Lampe sorgt für ein gutes Klima.Vermittelt positive Energie eine gesunde Atmosphäre, dient der Entspannung und fördert das Wohlbefinden.", 
    "name": "Klein Pyramide Salzkristall Lampe",  
    "saleprice": "30.99 €", 
    "oldprice": "35.00 €", 
    "slug": "pyramid-salt-lamp",  
    "size": "15x20 cm", 
    "weight": "2.5-3 kg", 
    "src": "../assets/img/portfolio/lamps/pyramid.png",   
    "title": "Klein Pyramide Salzkristall Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die Pyramide Salzlampe entzückt durch seine außergewöhnliche Form.Die Lampe fördert ein gutes Raumklima schafft eine gute Atmosphäre. Durchflutet den Raum mit wärmenden Licht. Sorgt für Entspannung, Stressabbau und dient zum Wohlbefinden.", 
    "name": "Groß Pyramide Salzkristall Lampe",  
    "saleprice": "31.99 €", 
    "oldprice": "35.00 €", 
    "slug": "pyramid-2-salt-lamp",  
    "size": "15x20 cm", 
    "weight": "2.5-3 kg", 
    "src": "../assets/img/portfolio/lamps/pyramid-2.jpg",   
    "title": "Groß Pyramide Salzkristall Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Der Kerzen Salzkristallhalter eignet sich auch vorzüglich als Candle-Light-Dinner. Kerzenlicht ist ein romantisches Licht, es sorgt für eine entspannde positive Atmosphäre. Auch fördert der Salzkristall ein gesundes Raumklima",     
    "name": "für drei Kerzen Salzkristall Halter",  
    "saleprice": "9.99 €", 
    "oldprice": "12.00 €", 
    "slug": "rectangular-salt-lamp",  
    "size": " 15x6 cm", 
    "weight": "1-1.5 kg", 
    "src": "../assets/img/portfolio/lamps/rectanular-1.png",   
    "title": "für drei Kerzen Salzkristall Halter by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Der Kerzensalzkristallhalter eignet sich vorzüglich für Festlichkeiten.Das romantische Kerzenlicht schafft eine schöne Atmosphäre und der Salzkristall sorgt für gutes Raumklima. ", 
    "name": "für vier Kerzen Salzkristall Halter",
    "saleprice": "19.99 €", 
    "oldprice": "22.00 €", 
    "slug": "rectangular-2-salt-lamp",  
    "size": "18x6 cm", 
    "weight": "1.5-2 kg", 
    "src": "../assets/img/portfolio/lamps/rectanular-2.png",   
    "title": "für vier Kerzen Salzkristall Halter by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Der Kerzenhalter besticht mit seiner schönen Form. Er schmückt jeden Tisch in jedem Raum.Der Salzkristall schafft ein gutes Raumklima und eine angenehme Atmosphäre", 
    "name": "für zwei Kerzen Salzkristall Halter",  
    "saleprice": "8.99 €", 
    "oldprice": "11.00 €", 
    "slug": "rectangular-3-salt-lamp",  
    "size": "10x6 cm ", 
    "weight": "1 kg", 
    "src": "../assets/img/portfolio/lamps/rectanular-3.png",   
    "title": "für zwei Kerzen Salzkristall Halter by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Der Kerzenalzkristallhalter gefällt durch seine Form..Er sorgt für gute Atmosphäre,gutes Raumklima und glückliche Menschen. Der Kerzenhalter wird gerne gekauft", 
    "name": "für fünf Kerzen Salzkristall Halter",  
    "saleprice": "22.50 €", 
    "oldprice": "25.00 €", 
    "slug": "rectangular-4-salt-lamp",  
    "size": "20x6 cm", 
    "weight": "2-2.5 kg", 
    "src": "../assets/img/portfolio/lamps/rectanular-4.png",   
    "title": "für fünf Kerzen Salzkristall Halter by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Die runde Salzkristalllampe beeindruckt durch ihre Form. Die Lampe durchflutet den Raum mit ihrem wärmenden Licht, sorgt für behagliche Atmosphäre, gute Stimmung und gute Schwingung. Der Salzkristall sorgt für ein gesundes Klima und für Entspannung.", 
    "name": "Runde Salzkristall Lampe",  
    "saleprice": "4.89 €", 
    "oldprice": "5.00 €", 
    "slug": "round-salt-lamp",  
    "size": "8-10 cm", 
    "weight": "1 kg", 
    "src": "../assets/img/portfolio/lamps/round.png",   
    "title": "Runde Salzkristall Lampe by Himalayan Salts" 
  }, 
  { 
    "category": "tiles", 
    "desc": "Der Runde Salzkristall Block ist vielseitig einsetzbar. Der runde Salzstein ist ein großartiger Natursalz Block. Ohne Schadstoffe, und Umweltgifte. Er wird aus der Tiefe des Himalaya Salzbergwerks gewonnen. Der Block ist ein Künstler für die Küche. Man kann ihn zum Einfrieren von Speisen verwenden.(-200°C). Sowie zum Anrichten für die kalte Speisen,z.B. für Wurst,Gemüse,Käse, Salat, Fisch usw. Was vor allen Dinge die Spitze ist man kann ihn als Grill einsetzen bei einer Wärme von 450°C. Also ein Gourmet Stein. Optisch sein Design ist überwältigend. Er ist Gesundheitsfördernd attraktiv und schafft zu dem noch ein gutes Raumklima.", 
    "name": "Runde Salzkristall Block",  
    "oldprice": "€24.99", 
    "saleprice": "€27.00", 
    "slug": "circular-salt-block",  
    "size": " 20x20x4 cm", 
    "weight": "3-3.5 kg", 
    "src": "../assets/img/portfolio/tiles/circle-block.jpg",   
    "title": "Runde Salzkristall Block by Himalayan Salts" 
  }, 
  { 
    "category": "tiles", 
    "desc": "Der rechteckige Salzkristallteller ist ein guter Therapeut in Ihrem Zuhause und hat einen niedrigen Stundenlohn. Die Salzkristallplatte ist bekannt für ihre Vielseitigkeit. Ein rechteckiges Himalaya-Salz aus einer Platte aus natürlichem festen Steinsalz ist ein Meister seines Fachs. Es passt gut in jeden Raum und wertet das Interieur Ihres Hauses auf. Sie ist ein optischer Meister in den glänzenden Räumen und zeichnet sich durch ihr schönes warmes Licht aus. Die Raumluft ist großartig und lässt Sie leicht atmen. Es vertreibt unangenehme Gerüche und lässt Sie sich in der guten Atmosphäre entspannen.", 
    "name": "Rechteckiger Salzziegel",  
    "oldprice": "€7.99", 
    "saleprice": "€10.00", 
    "slug": "rectangular-salt-brick", 
    "size": " 20x10x2.5 cm", 
    "weight": "1-1.5 kg",  
    "src": "../assets/img/portfolio/tiles/rect_brick.jpg",   
    "title": "Rechteckiger Salzziegel by Himalayan Salts" 
  }, 
  { 
    "category": "tiles", 
    "desc": "Die rechteckige Salzkristallplatte ist für seine Vielseitigkeit bekannt.Eine rechteckige Himalayasalzplatte aus  natürlichem festem Steinsalz,er ist ein Meister auf seinem Gebiet.Er passt gut in jeden Raum und verleiht dem Interieur ihres Hauses einen Mehrwert. Sowie in der Küche als auch zum verschönern der Innenräume ihres Hauses.Er ist ein optischer Meister in den  glänzenden Räumen und zeichnet sich durch sein schönes warmes Licht aus. Die Raumluft ist spitzenmäßig und lässt gut atmen.Der Salzkristall vertreibt schlechte Gerüche, lässt entspannen und vermittelt eine gute Atmosphäre. Die Platte in der Küche ist ein kleiner Gorment sie gibt einen leichten Salzgehalt ab ideal für alle Speisen. Die rechteckige Salzplatte ist eine notwendige Ergänzung für jede Küche, da vielseitig verwendbar, sei es zum Anbraten von Fleisch oder zum Kühl stellen von Speisen.",  
    "name": "Rechteckige Salzkristall Platte ",  
    "oldprice": "€24.00", 
    "saleprice": "€18.50", 
    "slug": "rectangular-salt-plate", 
    "size": "20x20x2.5 cm", 
    "weight": "kg", 
    "src": "../assets/img/portfolio/tiles/rect-plate.jpg",   
    "title": "Rechteckige Salzkristall Platte  by Himalayan Salts" 
  }, 
  { 
    "category": "tiles", 
    "desc": "Die runde Salzkristallplatte ist ein guter Innenarchitekt in ihrem Haus. Die Wertigkeit Ihres Hauses bekommt einen hohen Stellenwert. Der Individualität sind keine Grenzen gesetzt, dadurch wird das Flair ihres Haus hervorgehoben. Der kleine Runde Salzstein fördert die Gesundheit,schafft ein gutes Raumklima, eine positive Atmosphäre und lädt zum Relaxen ein.", 
    "name": "Runde Salzkristall Platte",  
    "oldprice": "€20.99", 
    "saleprice": "€25.00", 
    "slug": "circular-salt-tile",  
    "size": " 20x20x4 cm", 
    "weight": "3-3.5 kg", 
    "src": "../assets/img/portfolio/tiles/circle-2.png",   
    "title": "Runde Salzkristall Platte by Himalayan Salts" 
  }, 
  { 
    "category": "lick", 
    "desc": "Der Salzleckstein dient dem landwirtschaftlich Bereich.Er deckt exakt  den Mineralienbedarf eines Tieres ab. Ohne Mineralzufuhr kann ein Tier nicht leben. Trotz des täglichen Futters sollte man bei den Tieren darauf achten das optimale Leistungen und eine widerstandsfähige körperliche Verfassung gewährleistet sind. Sodass keine Mangelerscheinungen entstehen. Natrium erhält unter anderem den osmotischen Druck in den Zellen aufrecht es reguliert den Wasserhaushalt und spielt für die Impulsübertragung im Nervengewebe und in den Muskelfasern eine wichtige Rolle. Magnesium ist wichtig für die Muskel, Nervenfunktion und Knochenaufbau von Bedeutung. Calcium ist ein wesentlichen Bestandteil zur  Übertragung  von Nervenimpulsen und wird benötigt zum Knochenaufbau zur Blutgerinnung spielt es eine wichtige Rolle. Mangan ist erforderlich für den Mineral und Fettstoffwechsel. Zink ist ein essentieller Baustein von zahlreichen Proteinen fordert ein intaktes Immunsystem. Jod ist unentbehrlich für die Schilddrüsenfunktion und den Stoffwechseln. Kupfer hat eine wichtige Funktion für die Bildung von Nerven,Blut, Bindegewebe und Knochen. Selen ist ein Bestandteil von vielen Proteinen es ist wichtig für antioxidative Prozesse und der Jodstoffwechsel  ist  ein sogenannter Radikalfänger unersetzlich für den tierischen Organismus.", 
    "name": "Himalaya Salz Leckstein",  
    "oldprice": "€3.50/kg", 
    "saleprice": "€1.90/kg", 
    "slug": "animal-lick-salt", 
    "size": " cm", 
    "weight": "kg", 
    "src": "../assets/img/portfolio/lick/lick-1.png",   
    "title": "Himalaya Salz Leckstein by Himalayan Salts" 
  }, 
  { 
    "category": "lick", 
    "desc": "The Himalayan salt lick stone is used in agriculture and precisely covers the mineral requirements of an animal. An animal cannot live without mineral intake. Despite the daily feed, you should make sure that optimal performance and a resilient physical condition are guaranteed. So that there are no deficiency symptoms. Among other things, sodium maintains the osmotic pressure in the cells, it regulates the water balance and plays an important role in the transmission of impulses in nerve tissue and muscle fibers. Magnesium is important for muscle, nerve function and bone building. Calcium is an essential component for the transmission of nerve impulses and is required for building bones for blood clotting, it plays an important role. Magnesium is required for mineral and fat metabolism. Zinc is an essential component of numerous proteins which an intact immune system requires. Iodine is essential for thyroid function and metabolism. Copper plays an important role in the formation of nerves, blood, connective tissue and bones. Selenium is a component of many proteins, it is important for antioxidant processes and the iodine metabolism, it is a so-called radical scavenger, irreplaceable for the animal organism", 
    "name": "Himalaya Salz Leckstein",  
    "oldprice": "€3.50/kg", 
    "saleprice": "€1.90/kg", 
    "slug": "animal-2-lick-salt",  
    "src": "../assets/img/portfolio/lick/lick-2.png",   
    "title": "Himalaya Salz Leckstein by Himalayan Salts" 
  }, 
  { 
    "category": "lick", 
    "desc": "Der Himalaya Salzleckstein wird in der Landwirtschaft verwendet und deckt genau den Mineralstoffbedarf eines Tieres. Ein Tier kann ohne Mineralzufuhr nicht leben. Trotz der täglichen Fütterung sollten Sie darauf achten, dass eine optimale Leistung und eine belastbare körperliche Verfassung gewährleistet sind. Damit keine Mangelerscheinungen auftreten. Natrium hält unter anderem den osmotischen Druck in den Zellen aufrecht, reguliert den Wasserhaushalt und spielt eine wichtige Rolle bei der Impulsübertragung in Nervengewebe und Muskelfasern. Magnesium ist wichtig für die Muskel-, Nervenfunktion und den Knochenaufbau. Calcium ist ein wesentlicher Bestandteil für die Übertragung von Nervenimpulsen und wird für den Knochenaufbau für die Blutgerinnung benötigt, es spielt eine wichtige Rolle. Magnesium wird für den Mineral- und Fettstoffwechsel benötigt. Zink ist ein wesentlicher Bestandteil zahlreicher Proteine, die ein intaktes Immunsystem benötigt. Jod ist für die Schilddrüsenfunktion und den Stoffwechsel unerlässlich. Kupfer spielt eine wichtige Rolle bei der Bildung von Nerven, Blut, Bindegewebe und Knochen. Selen ist Bestandteil vieler Proteine, es ist wichtig für antioxidative Prozesse und den Jodstoffwechsel, es ist ein sogenannter Radikalfänger, unersetzlich für den tierischen Organismus", 
    "name": "Salzlecken Klumpen",  
    "oldprice": "€5.00/kg", 
    "saleprice": "€3.50/kg", 
    "slug": "salt-lick-lumps",  
    "src": "../assets/img/portfolio/lick/lick-lumps.png",   
    "title": "Salzlecken Klumpen by Himalayan Salts" 

  }]