const categories = {
  edible: "Edible Salts",
  lamps: "Salt Lamps",
  tiles: "Salt Tiles",
  lick: "Lick Salts"
}

const data = [
  {
    "category": "edible",
    "desc": "Pink Salt's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Pink Salt",
    "oldprice": "$100.00",
    "saleprice": "$50.00",
    "slug": "pink-salt",
    "src": "assets/img/portfolio/edible/ancient-ocean-himalayan-pink-salt-coarse-bowl.jpg",
    "title": "Pink Salt by Himalayan Salts"
  },
  {
    "category": "edible",
    "desc": "Fine Pink Salt's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Fine Pink Salt",
    "oldprice": "$70.00",
    "saleprice": "$30.00",
    "slug": "fine-pink-salt",
    "src": "assets/img/portfolio/edible/ancient-ocean-himalayan-pink-salt-fine-bowl.jpg",
    "title": "Fine Pink Salt by Himalayan Salts"
  },
  {
    "category": "edible",
    "desc": "Granular Pink Salt's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Granular Pink Salt", 
    "oldprice": "$80.00",
    "saleprice": "$40.00",
    "slug": "granular-pink-salt", 
    "src": "assets/img/portfolio/edible/ancient-ocean-himalayan-pink-salt-small-bowl.jpg",
    "title": "Granular Salt by Himalayan Salts"
  },
  {
    "category": "edible",
    "desc": "Iodized Salt's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Iodized Salt", 
    "oldprice": "$80.00",
    "saleprice": "$40.00",
    "slug": "iodized-salt", 
    "src": "assets/img/portfolio/edible/iodized-salt-fine-bowl.jpg",
    "title": "Iodized Salt by Himalayan Salts"
  },
  {
    "category": "edible",
    "desc": "Black Salt's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Black Salt", 
    "oldprice": "$80.00",
    "saleprice": "$40.00",
    "slug": "black-salt", 
    "src": "assets/img/portfolio/edible/kala-namak-indian-black-salt.jpg", 
    "title": "Black Salt by Himalayan Salts"
  },
  {
    "category": "edible",
    "desc": "Australian Sea Salt's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Australian Sea Salt", 
    "oldprice": "$80.00",
    "saleprice": "$40.00",
    "slug": "australian-sea-salt", 
    "src": "assets/img/portfolio/edible/paragon-australian-sea-salt-fine-bowl.jpg", 
    "title": "Australian Sea Salt by Himalayan Salts"
  },
  {
    "category": "edible",
    "desc": "Ocean Salt's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Ocean Salt", 
    "oldprice": "$80.00",
    "saleprice": "$40.00",
    "slug": "ocean-salt", 
    "src": "assets/img/portfolio/edible/pure-ocean-premium-sea-salt-fine-bulk-bowl.jpg", 
    "title": "Ocean Salt by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Angel lamp is amazing and gives the image of protection and enriches the healing powers of salt.",
    "name": "Angel Salt Lamp", 
    "saleprice": "30.00 €",
    "oldprice": "40.00 €",
    "slug": "angel-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/angel.png", 
    "title": "Angel Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Boat shaped lamp is the sign of hope and cure which won't even let the people sink or drown into any related disease.",
    "name": "Boat Salt Lamp", 
    "saleprice": "30.00 €",
    "oldprice": "40.00 €",
    "slug": "boat-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/boat.png", 
    "title": "Boat Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Bowl lamp not only decks the room with its light but due to its outstanding making captures the attention of the visitors due to its amazing and unique design.",
    "name": "Bowl Salt Lamp", 
    "saleprice": "35.00 €",
    "oldprice": "50.00 €",
    "slug": "bowl-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/bowl.png", 
    "title": "Bowl Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Giving the image of buring fire or coal makes it look further more eye catching and interesting.",
    "name": "Bowl Salt Lamp", 
    "saleprice": "35.00 €",
    "oldprice": "50.00 €",
    "slug": "bowl-2-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/bowl-2.jpg", 
    "title": "Bowl Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Bullet shaped salt can be installed in the room of the hunters or soldiers who love guns and bullets. Rather it would be a customized piece of art.",
    "name": "Bullet Salt Lamp", 
    "saleprice": "10.00 €",
    "oldprice": "20.00 €",
    "slug": "bullet-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/bullet.png",  
    "title": "Bullet Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Cactus lamp is an innovative design which attracts the attention due to its appeal towards natural elements. Another plus point is that it is smoother and soft unlike the thorny cactus.",
    "name": "Cactus Salt Lamp", 
    "saleprice": "30.00 €",
    "oldprice": "40.00 €",
    "slug": "cactus-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/cactus.png",  
    "title": "Cactus Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Cave lamp is high in demand due to its unique design which is very unique and romantic.",
    "name": "Cave Salt Lamp", 
    "saleprice": "30.00 €",
    "oldprice": "40.00 €",
    "slug": "cave-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/cave.png",  
    "title": "Cave Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "A high sale product of winters, which is loved by the adults but adored by the kids.",
    "name": "Christmas Tree Salt Lamp", 
    "saleprice": "35.00 €",
    "oldprice": "50.00 €",
    "slug": "christmas-tree-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/christmas-tree.png",  
    "title": "Christmas Tree Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Showing the trinity sign by keeping the bad luck away and purifying not only the body but soul as well.",
    "name": "Cross Salt Lamp", 
    "saleprice": "30.00 €",
    "oldprice": "40.00 €",
    "slug": "cross-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/cross.png",  
    "title": "Cross Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Its simply in a form of cube but the special thing is its natural design which is glorified by the lamp light.",
    "name": "Cubical Salt Lamp", 
    "saleprice": "17.00 €",
    "oldprice": "20.00 €",
    "slug": "cubical-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/cubical-1.jpg",  
    "title": "Cubical Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Further enhanced and polished cubical lamp is a treat to watch and gives a mesmerizing image.",
    "name": "Cubical Salt Lamp", 
    "saleprice": "18.00 €",
    "oldprice": "20.00 €",
    "slug": "cubical-2-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/cubical-2.png",  
    "title": "Cubical Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Innovation, impressive and eye catching design of the cubical checks is one of the favourate amongst the customers.",
    "name": "Cubical Salt Lamp", 
    "saleprice": "35.00 €",
    "oldprice": "50.00 €",
    "slug": "cubical-3-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/cubical-3.png",  
    "title": "Cubical Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Giving the image of buring candle looks so inspiring and realistic that at first glance you won't be able to guess whether it is a lamp or a burning candle.",
    "name": "Cylinderical Salt Lamp", 
    "saleprice": "25.00 €",
    "oldprice": "30.00 €",
    "slug": "cylinderical-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/cylinder.png",  
    "title": "Cylinderical Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Date Salt Lamp's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Date Salt Lamp", 
    "saleprice": "35.00 €",
    "oldprice": "50.00 €",
    "slug": "date-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/date.png",  
    "title": "Date Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "More refined image of the candle is the diamond candle with its unique and geomatrical shape.",
    "name": "Diamond Salt Lamp", 
    "saleprice": "25.00 €",
    "oldprice": "40.00 €",
    "slug": "diamond-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/diamond.png",  
    "title": "Diamond Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Fine edged piece of art with finely refined edges shows its perfection by its brilliant design.",
    "name": "Diamond Salt Lamp", 
    "saleprice": "30.00 €",
    "oldprice": "40.00 €",
    "slug": "diamond-2-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/dimaond-2.png",  
    "title": "Diamond Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "You spend Euros and Dollars and in return we'll provide you with such an innovative Dollar shaped piece of art that will stay with you forever and wont leave your room.",
    "name": "Dollar Salt Lamp", 
    "saleprice": "25.00 €",
    "oldprice": "40.00 €",
    "slug": "dollar-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/dollar.png",  
    "title": "Dollar Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Drum lamp is innovative and gives the musical effect which is very unique and pleasing.",
    "name": "Drum Salt Lamp", 
    "saleprice": "25.00 €",
    "oldprice": "40.00 €",
    "slug": "drum-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/drum.png",  
    "title": "Drum Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Egg showing the sign of life and hope, keeps you optamistic towards life ",
    "name": "Egg Salt Lamp", 
    "saleprice": "35.00 €",
    "oldprice": "50.00 €",
    "slug": "egg-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/egg.png",  
    "title": "Egg Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Eye lamp is very impressive and eye-catching because of its fine finishing and grand design.",
    "name": "Eye Salt Lamp", 
    "saleprice": "12.00 €",
    "oldprice": "15.00 €",
    "slug": "eye-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/eye.png",  
    "title": "Eye Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Fire Bowl Salt Lamp's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Fire Bowl Salt Lamp", 
    "saleprice": "35.00 €",
    "oldprice": "50.00 €",
    "slug": "fire-bowl-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/fire-bowl.png",  
    "title": "Fire Bowl Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Giving the image of flame gives the feeling of freshness and warmth.",
    "name": "Flame Salt Lamp", 
    "saleprice": "30.00 €",
    "oldprice": "40.00 €",
    "slug": "flame-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/flame.png",  
    "title": "Flame Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Appeal towards the nature by taking this amazing show piece with you which can sooth your heart and cure your aches.",
    "name": "Flower Salt Lamp", 
    "saleprice": "35.00 €",
    "oldprice": "50.00 €",
    "slug": "flower-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/flower.png",  
    "title": "Flower Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Flower Salt Lamp's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Flower Salt Lamp", 
    "saleprice": "35.00 €",
    "oldprice": "50.00 €",
    "slug": "flower-2-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/flower-2.png",  
    "title": "Flower Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Fort lamp shows grandeur and courageous is a best gift for the daring and courageous people. On the other hand, its design is also very appealing.",
    "name": "Fort Salt Lamp", 
    "saleprice": "35.00 €",
    "oldprice": "50.00 €",
    "slug": "fort-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/fort.png",  
    "title": "Fort Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Globe design is so round, fine and appealing that the customers love to touch it and it at once relaxes them.",
    "name": "Globe Salt Lamp", 
    "saleprice": "29.00 €",
    "oldprice": "40.00 €",
    "slug": "globe-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/globe-1.jpg",  
    "title": "Globe Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "This dark pink salt globe is without light because of its unique and heavy natural design.",
    "name": "Globe Salt Lamp", 
    "saleprice": "25.00 €",
    "oldprice": "40.00 €",
    "slug": "globe-2-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/globe-2.png",  
    "title": "Globe Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Burning heart candle can set ablaze to the hearts of the lovers and can be best used for the candle lit dinners along with petal decoration.",
    "name": "Heart Salt Lamp", 
    "saleprice": "10.00 €",
    "oldprice": "15.00 €",
    "slug": "heart-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/heart.png",  
    "title": "Heart Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Heart lamp is another amazing treat for the lovers and can be the best gift for the ones you love the most, to show your warmth and affection to them.",
    "name": "Heart Salt Lamp", 
    "saleprice": "30.00 €",
    "oldprice": "40.00 €",
    "slug": "heart-2-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/heart-2.png",  
    "title": "Heart Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Two dimentional leaf is apealing with its sleek cuts, giving it the proper blend of light and dark shades of salt, which make the leaf look further more realistic.",
    "name": "Leaf Salt Lamp", 
    "saleprice": "35.00 €",
    "oldprice": "50.00 €",
    "slug": "leaf-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/leaf.png",
    "title": "Leaf Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Amazing piece of art with innovative outline of the leaf, along with the centre occupied with the candle ",
    "name": "Leaf Salt Lamp", 
    "saleprice": "30.00 €",
    "oldprice": "40.00 €",
    "slug": "leaf-2-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/leaf-2.png",  
    "title": "Leaf Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Lotus Salt Lamp's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Lotus Salt Lamp", 
    "saleprice": "35.00 €",
    "oldprice": "50.00 €",
    "slug": "lotus-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/lotus.png",  
    "title": "Lotus Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Mushroom lovers, here is another customized show piece for you, to make you smile and your day bright.",
    "name": "Mushroom Salt Lamp", 
    "saleprice": "30.00 €",
    "oldprice": "40.00 €",
    "slug": "mushroom-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/mushroom.png",  
    "title": "Mushroom Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Natural Salt Lamp's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Natural Salt Lamp", 
    "saleprice": "30.00 €",
    "oldprice": "40.00 €",
    "slug": "natural-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/natural-1.png",  
    "title": "Natural Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Impressive geomatrical shape with the glow and shiny effect from within.",
    "name": "Octane Salt Lamp", 
    "saleprice": "35.00 €",
    "oldprice": "50.00 €",
    "slug": "octane-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/octacone.png",  
    "title": "Octane Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Cylinder like image with variety of colours due to its natural God-gifted designing.",
    "name": "Orchid Salt Lamp", 
    "saleprice": "35.00 €",
    "oldprice": "50.00 €",
    "slug": "orchid-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/orchid.png",  
    "title": "Orchid Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Oval design is unique and fashionable with its rough cuttings and sleek designing.",
    "name": "Oval Salt Lamp", 
    "saleprice": "30.00 €",
    "oldprice": "40.00 €",
    "slug": "oval-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/oval.jpg",  
    "title": "Oval Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Palm Salt Lamp's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Palm Salt Lamp", 
    "saleprice": "35.00 €",
    "oldprice": "50.00 €",
    "slug": "palm-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/palm.png",  
    "title": "Palm Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Pyramid Salt Lamp's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Pyramid Salt Lamp", 
    "saleprice": "35.00 €",
    "oldprice": "50.00 €",
    "slug": "pyramid-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/pyramid.png",  
    "title": "Pyramid Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Pyramid Salt Lamp's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Pyramid Salt Lamp", 
    "saleprice": "35.00 €",
    "oldprice": "50.00 €",
    "slug": "pyramid-2-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/pyramid-2.jpg",  
    "title": "Pyramid Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Mini four candle salt module makes it so innovative and eye catching for the customers.",
    "name": "Rectangular Salt Lamp", 
    "saleprice": "35.00 €",
    "oldprice": "50.00 €",
    "slug": "rectangular-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/rectanular-1.png",  
    "title": "Rectangular Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Rectangular Salt Lamp's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Rectangular Salt Lamp", 
    "saleprice": "35.00 €",
    "oldprice": "50.00 €",
    "slug": "rectangular-2-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/rectanular-2.png",  
    "title": "Rectangular Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Rectangular Salt Lamp's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Rectangular Salt Lamp", 
    "saleprice": "35.00 €",
    "oldprice": "50.00 €",
    "slug": "rectangular-3-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/rectanular-3.png",  
    "title": "Rectangular Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Rectangular Salt Lamp's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Rectangular Salt Lamp", 
    "saleprice": "35.00 €",
    "oldprice": "50.00 €",
    "slug": "rectangular-4-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/rectanular-4.png",  
    "title": "Rectangular Salt Lamp by Himalayan Salts"
  },
  {
    "category": "lamps",
    "desc": "Round Salt Lamp's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Round Salt Lamp", 
    "saleprice": "30.00 €",
    "oldprice": "40.00 €",
    "slug": "round-salt-lamp", 
    "size": "6-8 inch",
    "weight": "3-5 kg",
    "src": "assets/img/portfolio/lamps/round.png",  
    "title": "Round Salt Lamp by Himalayan Salts"
  },
  {
    "category": "tiles",
    "desc": "Circular Salt Block's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Circular Salt Block", 
    "oldprice": "$80.00",
    "saleprice": "$40.00",
    "slug": "circular-salt-block", 
    "src": "assets/img/portfolio/tiles/circle-block.jpg",  
    "title": "Circular Salt Block by Himalayan Salts"
  },
  {
    "category": "tiles",
    "desc": "Rectangular Salt Brick's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Rectangular Salt Brick", 
    "oldprice": "$80.00",
    "saleprice": "$40.00",
    "slug": "rectangular-salt-brick", 
    "src": "assets/img/portfolio/tiles/rect_brick.jpg",  
    "title": "Rectangular Salt Brick by Himalayan Salts"
  },
  {
    "category": "tiles",
    "desc": "Rectangular Salt Plate's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Rectangular Salt Plate", 
    "oldprice": "$80.00",
    "saleprice": "$40.00",
    "slug": "rectangular-salt-plate", 
    "src": "assets/img/portfolio/tiles/rect-plate.jpg",  
    "title": "Rectangular Salt Plate by Himalayan Salts"
  },
  {
    "category": "tiles",
    "desc": "Circular Salt Tile's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Circular Salt Tile", 
    "oldprice": "$80.00",
    "saleprice": "$40.00",
    "slug": "circular-salt-tile", 
    "src": "assets/img/portfolio/tiles/circle-2.png",  
    "title": "Circular Salt Tile by Himalayan Salts"
  },
  {
    "category": "lick",
    "desc": "Animal Lick Salt's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Animal Lick Salt", 
    "oldprice": "$80.00",
    "saleprice": "$40.00",
    "slug": "animal-lick-salt", 
    "src": "assets/img/portfolio/lick/lick-1.png",  
    "title": "Animal Lick Salt by Himalayan Salts"
  },
  {
    "category": "lick",
    "desc": "Animal Lick Salt's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Animal Lick Salt", 
    "oldprice": "$80.00",
    "saleprice": "$40.00",
    "slug": "animal-2-lick-salt", 
    "src": "assets/img/portfolio/lick/lick-2.png",  
    "title": "Animal Lick Salt by Himalayan Salts"
  },
  {
    "category": "lick",
    "desc": "Salt Lick Lump's decription. Integer auctor purus a lectus suscipit fermentum. Vivamus lobortis",
    "name": "Salt Lick Lump", 
    "oldprice": "$80.00",
    "saleprice": "$40.00",
    "slug": "salt-lick-lumps", 
    "src": "assets/img/portfolio/lick/lick-lumps.png",  
    "title": "Salt Lick Lump by Himalayan Salts"
  }



]