const categories = { 
  edible: "Edible Salts", 
  lamps: "Salt Lamps", 
  tiles: "Salt Tiles", 
  lick: "Lick Salts" 
} 
 
const data = [ 
  { 
    "category": "edible", 
    "desc": " Coarse pure pink Himalayan salt is unrefined and therefore  100% natural. Himalayan salt is the purest form of salt and contains minerals that are very important for the human body. Pink coloured Himalayan salt gets its colour from the iron content. The occurrence and the degradation methods guarantee a particularly high level of purity. This is the big difference between Himalayan salt and sea salt. Himalaya salt guarantees 100% purity, and the sea salt is contaminated with microplastics as well as environmental toxins from petroleum residues and other pollution. This alone is a plea in favour of Himalayan salt as there are no environmental toxins to be found. In addition, it stands out from conventional table salts thanks to its beautiful colour. It is well known from the published book 2001 “Water & Salt: The Essence of Life”. Water and salt are essential for our existence. The vital position of salt depends on the properties of the salt. It is good for flavouring the kitchen. One can also have a beauty day because it is an excellent bath salt. We offer Himalayan salt in two different colours, light pink and dark pink. The coarse pink Himalayan salt is between 2-5 mm in size.", 
    "name": " Coarse pure pink Himalayan Salt", 
    "oldprice": "€3.50/kg", 
    "saleprice": "€2.79/kg", 
    "slug": "pink-salt", 
    "src": "assets/img/portfolio/edible/ancient-ocean-himalayan-pink-salt-coarse-bowl.jpg", 
    "title": "Pink Salt by Himalayan Salts" 
  }, 
  { 
    "category": "edible", 
    "desc": "Fine pink Himalayan salt is unrefined and therefore 100% natural. Himalayan salt is the purest form of salt and contains minerals that are very important for the human body. Pink coloured Himalayan salt gets its colour from the iron content. The occurrence and the degradation methods guarantee a particularly high level of purity. This is the big difference between Himalayan salt and sea salt. Himalaya salt guarantees 100% purity, and the sea salt is contaminated with microplastics as well as environmental toxins from petroleum residues and other pollution. This alone is a plea in favour of Himalayan salt as there are no environmental toxins to be found. In addition, it stands out from conventional table salts thanks to its beautiful colour. It is well known from the published book 2001 “Water & Salt: The Essence of Life”. Water and salt are essential for our existence. The vital position of salt depends on the properties of the salt. It is good for flavouring the kitchen. One can also have a beauty day because it is an excellent bath salt. We offer Himalayan salt in two different colours, light pink and dark pink. The fine pink Himalayan salt is between 0.2-1 mm in size", 
    "name": "Fine Pink Salt", 
    "oldprice": "€ 3.60/kg ", 
    "saleprice": "€3.00/kg", 
    "slug": "fine-pink-salt", 
    "src": "assets/img/portfolio/edible/ancient-ocean-himalayan-pink-salt-fine-bowl.jpg", 
    "title": "Fine Pink Salt by Himalayan Salts" 
  }, 
  { 
    "category": "edible", 
    "desc": "Granular Himalayan salt is unrefined and therefore 100% natural. Himalayan salt is the purest form of salt and contains minerals that are very important for the human body. Pink coloured Himalayan salt gets its colour from the iron content. The occurrence and the degradation methods guarantee a particularly high level of purity. This is the big difference between Himalayan salt and sea salt. Himalaya salt guarantees 100% purity, and the sea salt is contaminated with microplastics as well as environmental toxins from petroleum residues and other pollution. This alone is a plea in favour of Himalayan salt as there are no environmental toxins to be found. In addition, it stands out from conventional table salts thanks to its beautiful colour. It is well known from the published book 2001 “Water & Salt: The Essence of Life”. Water and salt are essential for our existence. The vital position of salt depends on the properties of the salt. It is good for flavouring the kitchen. One can also have a beauty day because it is an excellent bath salt. The granular pink Himalayan salt is between 1-4 mm in size", 
    "name": "Granular Pink Salt",  
    "oldprice": "€3.99/kg ", 
    "saleprice": "€3.55/kg ", 
    "slug": "granular-pink-salt",  
    "src": "assets/img/portfolio/edible/ancient-ocean-himalayan-pink-salt-small-bowl.jpg", 
    "title": "Granular Salt by Himalayan Salts" 
  }, 
  { 
    "category": "edible", 
    "desc": "Not available at the moment", 
    "name": "Iodized Salt",  
    "oldprice": "€3.50/kg ", 
    "saleprice": "€3.00/kg ", 
    "slug": "iodized-salt",  
    "src": "assets/img/portfolio/edible/iodized-salt-fine-bowl.jpg", 
    "title": "Iodized Salt by Himalayan Salts" 
  }, 
  { 
    "category": "edible", 
    "desc": " Himalayan black salt is also known as Black salt, Kala Namak (in Urdu) and Kala Loon (in Punjabi). It runs under the Ayurvedic food chain and is health-promoting, and it is also popular in vegan cuisine. The black salt comes from India/Pakistan, it consists of 98% sodium chloride and has several mineral components that are very important for the human body. The black salt lowers blood pressure and is recommended for a low-salt diet. Food with fruits has a rounded taste thanks to the seasoning of black salt, which is of great importance in Indian medicine. It is used especially for drinks in hot countries because it has an isotonic effect. It is suitable and recommended for athletes and for people with great activities to cover the mineral balance. Heartburn problems are easy to control.", 
    "name": "Black Salt",  
    "oldprice": "€9.00/500g", 
    "saleprice": "€7.5/500g ", 
    "slug": "black-salt",  
    "src": "assets/img/portfolio/edible/kala-namak-indian-black-salt.jpg",  
    "title": "Black Salt by Himalayan Salts" 
  }, 
  { 
    "category": "edible", 
    "desc": "Not available!", 
    "name": "Australian Sea Salt",  
    "oldprice": "€20.00/500g", 
    "saleprice": "€19.00/500g", 
    "slug": "australian-sea-salt",  
    "src": "assets/img/portfolio/edible/paragon-australian-sea-salt-fine-bowl.jpg",  
    "title": "Australian Sea Salt by Himalayan Salts" 
  }, 
  { 
    "category": "edible", 
    "desc": " Not available!", 
    "name": "Ocean Salt",  
    "oldprice": "€20.00", 
    "saleprice": "€18.00", 
    "slug": "ocean-salt",  
    "src": "assets/img/portfolio/edible/pure-ocean-premium-sea-salt-fine-bulk-bowl.jpg",  
    "title": "Ocean Salt by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Angel sign gives you the feeling of trust,protection and blessing in your life. The lamp looks amazing and gives the image of protection, spirituality and enriches the healing powers of salt. These vibrational vibes by your side help you to fulfill your life mission. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Angel Salt Lamp",  
    "saleprice": "30.99 €", 
    "oldprice": "35.00 €", 
    "slug": "angel-salt-lamp",  
    "size": "20x15x7cm", 
    "weight": "2.5-3 kg", 
    "src": "assets/img/portfolio/lamps/angel.png",  
    "title": "Angel Salt Lamp by Himalayan Salts" 

  }, 
  { 
    "category": "lamps", 
    "desc": " The salt lamp boat provides a wonderful room atmosphere and a healthy indoor climate. It is reminiscent of the longing for leisure, vacation and hope. It provides healing and doesn't make people sink or drown in a disease. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Boat Salt Lamp",  
    "saleprice": "37.99 €", 
    "oldprice": "39.99 €", 
    "slug": "boat-salt-lamp",  
    "size": "15x15cm", 
    "weight": "2.5-3 kg", 
    "src": "assets/img/portfolio/lamps/boat.png",  
    "title": "Boat Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "This bowl lamp reflects a wonderful atmosphere and ensures a healthy indoor climate. It invites you to relax and unwind, As well as to the wellbeing.The bowl lamp not only decorates the room with its light, but also attracts the attention of visitors. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Bowl Salt Lamp",  
    "saleprice": "22.99 €", 
    "oldprice": "25.00 €", 
    "slug": "bowl-salt-lamp",  
    "size": "15x15 cm", 
    "weight": "2-2.5 kg", 
    "src": "assets/img/portfolio/lamps/bowl.png",  
    "title": "Bowl Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Giving the image of buring fire or coal makes it look further relaxing and conjuring up warmth and comfort in the room. Here too, the indoor climate is beneficial to your health, it lets you breathe deeply and relax. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Bowl Salt Lamp",  
    "saleprice": "30.99 €", 
    "oldprice": "35.00 €", 
    "slug": "bowl-2-salt-lamp",  
    "size": "15x10x15 cm", 
    "weight": "3-3.5 kg", 
    "src": "assets/img/portfolio/lamps/bowl-2.jpg",  
    "title": "Bowl Salt Lamp by Himalayan Salts" 

  }, 
  { 
    "category": "lamps", 
    "desc": " This little salt lamp improves your indoor climate and promotes your health. It invites you to relax and feel good and floods your room with a warming light. This salt lamp can be installed in the room of the hunters or soldiers who are in love with guns and bullets.", 
    "name": "Bullet Candle Holder",  
    "saleprice": "4.89 €", 
    "oldprice": "5.00 €", 
    "slug": "bullet-salt-lamp",  
    "size": "8-10 cm", 
    "weight": "1 kg", 
    "src": "assets/img/portfolio/lamps/bullet.png",   
    "title": "Bullet Salt Lamp by Himalayan Salts" 

  }, 
  { 
    "category": "lamps", 
    "desc": "The cactus lamp enchants your room. It creates a better atmosphere through a healthier indoor climate. Helps to remove smoke and other harmful substances and reduces allergies. It brings a warming light and makes room an oasis of well-being.It appeals because of its natural look. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Cactus Salt Lamp",  
    "saleprice": "30.99 €", 
    "oldprice": "35.00 €", 
    "slug": "cactus-salt-lamp",  
    "size": "15-20 cm", 
    "weight": "2.5-3 kg", 
    "src": "assets/img/portfolio/lamps/cactus.png",   
    "title": "Cactus Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": " The cave lamp is unique. A sign of warmth and security, it improves the indoor climate, helps better breathing and reduces allergies. Makes you feel good and relaxed. You feel like you are in the fresh air. Cave lamp is high in demand due to its unique design. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Cave Salt Lamp",  
    "saleprice": "18.99 €", 
    "oldprice": "20.00 €", 
    "slug": "cave-salt-lamp",  
    "size": "10x11x13 cm", 
    "weight": "1.5-2 kg", 
    "src": "assets/img/portfolio/lamps/cave.png",   
    "title": "Cave Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "The Christmas tree salt lamp makes us think of Christmas. It is specifically a winter product that is loved by both, adults and children. It improves the indoor climate and arouses feelings like a walk in the forest. You feel like you are in the fresh air, with a cozy light. It relaxes, makes you feel good, like a healing therapy. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Christmas Tree Salt Lamp",  
    "saleprice": "28.99 €", 
    "oldprice": "30.00 €", 
    "slug": "christmas-tree-salt-lamp",  
    "size": "17-20 cm", 
    "weight": "2-2.5 kg", 
    "src": "assets/img/portfolio/lamps/christmas-tree.png",   
    "title": "Christmas Tree Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "The cross is the symbol of Christianity, it stands for love, peace, justice and forgiveness by keeping away the bad luck and purifying not only the body but soul as well. The salt lamp improves the room climate, provides a pleasant light and provides a feeling of security. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Cross Salt Lamp",  
    "saleprice": "40.99 €", 
    "oldprice": "45.00 €", 
    "slug": "cross-salt-lamp",  
    "size": "25x25x10 cm", 
    "weight": "2-2.5 kg", 
    "src": "assets/img/portfolio/lamps/cross.png",   
    "title": "Cross Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": " The cubic salt lamp impresses with its shape. It improves the indoor climate, creates a great atmosphere to relax and feel good. The cubic lamp not only decorates the room with its light, but also attracts the attention of visitors. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Cubical Salt Lamp",  
    "saleprice": "50.99 €", 
    "oldprice": "60.00 €", 
    "slug": "cubical-salt-lamp",  
    "size": "20x20x24 cm", 
    "weight": "4.5-6 kg", 
    "src": "assets/img/portfolio/lamps/cubical-1.jpg",   
    "title": "Cubical Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "The fine polished cubical lamp is an eyecatcher and gives a mesmerizing look.The cubic salt lamp impresses with its shape. It improves the indoor climate, creates a great atmosphere to relax and feel good. The cubic lamp not only decorates the room with its light, but also attracts the attention of visitors. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Cubical Salt Lamp",  
    "saleprice": "27.99 €", 
    "oldprice": "28.99 €", 
    "slug": "cubical-2-salt-lamp",  
    "size": "10x10x12 cm", 
    "weight": "2-2.5 kg", 
    "src": "assets/img/portfolio/lamps/cubical-2.png",   
    "title": "Cubical Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "The cubical lamp with checks is an eye catching and innovative design. It gives a mesmerizing look and impresses everybody with its shape. It improves the indoor climate, creates a great atmosphere to relax and feel good. It is one of the favourites amongst the customers. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Cubical Salt Lamp",  
    "saleprice": "55.99 €", 
    "oldprice": "65.00 €", 
    "slug": "cubical-3-salt-lamp",  
    "size": "20x20x24 cm", 
    "weight": "4.5-6 kg", 
    "src": "assets/img/portfolio/lamps/cubical-3.png",   
    "title": "Cubical Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "The cylindrical salt lamp improve the room air management for comfortable breathing and give a light of security. Giving the image of a burning candle looks so inspiring and realistic that at first glance you cannot guess whether it is a lamp or a burning candle. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Cylinderical Salt Lamp",  
    "saleprice": "24.99 €", 
    "oldprice": "30.00 €", 
    "slug": "cylinderical-salt-lamp",  
    "size": "16x10 cm", 
    "weight": "2-2.5 kg", 
    "src": "assets/img/portfolio/lamps/cylinder.png",   
    "title": "Cylinderical Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "The date lamp due to its shape, gives off a warm light. Improve the indoor air feel for a nice atmosphere to relax and be happy. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Date Salt Lamp",  
    "saleprice": "35.99 €", 
    "oldprice": "40.00 €", 
    "slug": "date-salt-lamp",  
    "size": "15x15x10 cm", 
    "weight": "2-2.5 kg", 
    "src": "assets/img/portfolio/lamps/date.png",   
    "title": "Date Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "For us too, the diamond salt lamp is like a cut candle diamond. The lamp creates a feel-good atmosphere. It preserves the soul through its light and ensures relaxation and security. This is the more refined image of the candle with its unique and geometric shape.", 
    "name": "Diamond Salt Lamp",  
    "saleprice": "17.99 €", 
    "oldprice": "23.00 €", 
    "slug": "diamond-salt-lamp",  
    "size": "15x12x12 cm", 
    "weight": "2.5-3 kg", 
    "src": "assets/img/portfolio/lamps/diamond.png",   
    "title": "Diamond Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "The diamond salt lamp is the diamond among the salt lamps. The lamp impresses with its color and improves the air in the room. The salt lamp creates a wonderful atmosphere. It lets calm and security flow into the room and gives a light of security and creates a positive atmosphere. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Diamond Salt Lamp",  
    "saleprice": "24.99 €", 
    "oldprice": "27.00 €", 
    "slug": "diamond-2-salt-lamp",  
    "size": "15x12x12 cm", 
    "weight": "2.5-3 kg", 
    "src": "assets/img/portfolio/lamps/dimaond-2.png",   
    "title": "Diamond Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": " Dollar lamp always at home! No EMERGENCY and always bread around.! This little work of art inspired by its shape ensures good indoor air and a good atmosphere of well-being and security.", 
    "name": "Dollar Himalaya Salt",  
    "saleprice": "12.99 €", 
    "oldprice": "15.00 €", 
    "slug": "dollar-salt-lamp",  
    "size": "10x10x7 cm", 
    "weight": "2.5-3 kg", 
    "src": "assets/img/portfolio/lamps/dollar.png",   
    "title": "Dollar Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": " The drum candle lamp is innovative and gives the music lover the desired atmosphere, ensures good room air for relaxation, security and satisfaction. The drum salt lamp is an eye-catcher for everyone. Will you make some room for a drum salt lamp.", 
    "name": "Drum Salt Lamp",  
    "saleprice": "20.99 €", 
    "oldprice": "25.00 €", 
    "slug": "drum-salt-lamp",  
    "size": "15x15x15 cm", 
    "weight": "1-1.5 kg", 
    "src": "assets/img/portfolio/lamps/drum.png",   
    "title": "Drum Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": " This lamp is a symbol of life and diversity, it ensures good room air, a wonderful atmosphere, the lamp conveys the feeling of relaxation and security. Due to its delightful shape, it is sold quite often. Includes 1 light bulb,1 m cable with socket and wooden base. ", 
    "name": "Egg Salt Lamp",  
    "saleprice": "30.99 €", 
    "oldprice": "35.00 €", 
    "slug": "egg-salt-lamp",  
    "size": "15x15 cm", 
    "weight": "2.5-3.5 kg", 
    "src": "assets/img/portfolio/lamps/egg.png",   
    "title": "Egg Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Eye candle lamp is very impressive and eye-catching because of its fine finishing and grand design. This small lamp also improves your room climate and creates a wonderful atmosphere to make you feel good and relaxed.", 
    "name": "Eye Salt Lamp",  
    "saleprice": "9.99 €", 
    "oldprice": "13.00 €", 
    "slug": "eye-salt-lamp",  
    "size": "13x8x5 cm", 
    "weight": "1-1.5 kg", 
    "src": "assets/img/portfolio/lamps/eye.png",   
    "title": "Eye Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "The fire bowl lamp gives every room a very special atmosphere. Salt crystal lamp not only emits warm light, it is also said to have positive properties on our health. It improves the indoor climate, creates a positive atmosphere and invites you to relax. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Fire Bowl Salt Lamp",  
    "saleprice": "30.99 €", 
    "oldprice": "35.00 €", 
    "slug": "fire-bowl-salt-lamp",  
    "size": "15x10x10 cm", 
    "weight": "3-3.5 kg", 
    "src": "assets/img/portfolio/lamps/fire-bowl.png",   
    "title": "Fire Bowl Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "Giving the image of flame, it gives the feeling of freshness and warmth. The salt candle lamp ensures a good indoor climate and has a relaxing effect. The warm orange light of the lamp is worth encouraging and relaxing. Salt attracts moisture and absorbs moisture. The red-orange light spectrum helps reduce stress.", 
    "name": "Flame Salt Lamp",  
    "saleprice": "10.99 €", 
    "oldprice": "12.00 €", 
    "slug": "flame-salt-lamp",  
    "size": "10x8 cm", 
    "weight": "1 kg", 
    "src": "assets/img/portfolio/lamps/flame.png",   
    "title": "Flame Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": " The flower crystal salt lamp creates a floral atmosphere with a warm light spectrum, improves the room climate and conveys the feeling of freshness and warmth. It invites you to dream, you feel like you are in the garden.", 
    "name": "Flower Salt Lamp",  
    "saleprice": "10.99 €", 
    "oldprice": "15.00 €", 
    "slug": "flower-salt-lamp",  
    "size": "10x10x10 cm", 
    "weight": "1-1.5 kg", 
    "src": "assets/img/portfolio/lamps/flower.png",   
    "title": "Flower Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "The salt crystal lamp has the shape of a rose. It impresses with its design. When it shines with its orange light, it creates a good room climate, improves energy, ensures relaxation, reduces sleep disorders and reduces stress. The flower crystal salt lamp creates a floral atmosphere with a warm light spectrum. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Flower Salt Lamp",  
    "saleprice": "33.99 €", 
    "oldprice": "36.00 €", 
    "slug": "flower-2-salt-lamp",  
    "size": "20x15 cm", 
    "weight": "3-3.5 kg", 
    "src": "assets/img/portfolio/lamps/flower-2.png",   
    "title": "Flower Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": " The Fort salt crystal lamp impresses with its design. It is intended for brave people. The lamp conveys strength and is free from environmental toxins. It improves the indoor climate and creates a positive atmosphere. Fort is the sign of courage and is a best gift for the courageous people. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Fort Salt Lamp",  
    "saleprice": "40.99 €", 
    "oldprice": "45.00 €", 
    "slug": "fort-salt-lamp",  
    "size": "20-25 cm", 
    "weight": "3-3.5 kg", 
    "src": "assets/img/portfolio/lamps/fort.png",   
    "title": "Fort Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": " The Globe crystal lamp impresses with its design. Its yellow-orange light releases positive energy. The lamp improves the room climate, ensures relaxation and a feel-good atmosphere. It is a popular product from customers. It is so round, fine and appealing that the customers love to touch it. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Globe Salt Lamp",  
    "saleprice": "35.99 €", 
    "oldprice": "40.00 €", 
    "slug": "globe-salt-lamp",  
    "size": "15x15 cm", 
    "weight": "2.5-3 kg", 
    "src": "assets/img/portfolio/lamps/globe-1.jpg",   
    "title": "Globe Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": " This lamp is a great natural product because the salt crystal trunk comes from the Himalayas. The salt crystal is known for its health-promoting effects, and it is also said to ensure harmony and inner balance. it improves the indoor climate and creates a positive atmosphere.Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Globe Salt Lamp",  
    "saleprice": "30.99 €", 
    "oldprice": "35.00 €", 
    "slug": "globe-2-salt-lamp",  
    "size": "15x15 cm", 
    "weight": "2.5-3 kg", 
    "src": "assets/img/portfolio/lamps/globe-2.png",   
    "title": "Globe Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": " The heart salt crystals speak for romance and love. It stands for trust and affection. The Himalayan salt improves the indoor climate, creates a harmonious atmosphere and is a great decoration for every room. It can be used for candlelight dinner along with the petal decorations.", 
    "name": "Heart Salt Lamp",  
    "saleprice": "9.99 €", 
    "oldprice": "11.00 €", 
    "slug": "heart-salt-lamp",  
    "size": "10x10 cm", 
    "weight": "1 kg", 
    "src": "assets/img/portfolio/lamps/heart.png",   
    "title": "Heart Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": " This lamp is ideal for a candlelight dinner. It creates an excellent atmosphere, positive energy, connects hearts, sends warmth and sparks. It is a symbol of love, the lamp improves the rooms climate, lets you relax, demands the lightness of happiness. Heart lamp is another amazing treat for the lovers and can be the best gift for the ones you love the most. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Heart Salt Lamp",  
    "saleprice": "42.99 €", 
    "oldprice": "45.00 €", 
    "slug": "heart-2-salt-lamp",  
    "size": "10x17x17 cm", 
    "weight": "3-3.5 kg", 
    "src": "assets/img/portfolio/lamps/heart-2.png",   
    "title": "Heart Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "The leaf salt crystal lamp impresses with its design; it is health-promoting, improves the room climate and calls for positive energy. The lamp serves to relax, relieves stress, ensures well-being. Inspires for a walk in the woods. The leaf design is appealing which make the leaf look furthermore realistic. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Leaf Salt Lamp",  
    "saleprice": "34.99 €", 
    "oldprice": "40.00 €", 
    "slug": "leaf-salt-lamp",  
    "size": "15x20 cm", 
    "weight": "2.5-3 kg", 
    "src": "assets/img/portfolio/lamps/leaf.png", 
    "title": "Leaf Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "The leaf salt crystal lamp has the shape of a candle. It throws a warm, comfortable light into the room. The lamp seduces you to relax, promotes well-being, improves the room climate, provides positive energy and creates a good atmosphere. It is an amazing piece of art with outline of the leaf and centre occupied with the candle", 
    "name": "Leaf Salt Lamp",  
    "saleprice": "17.99 €", 
    "oldprice": "20.00 €", 
    "slug": "leaf-2-salt-lamp",  
    "size": "10x12 cm", 
    "weight": "1 kg", 
    "src": "assets/img/portfolio/lamps/leaf-2.png",   
    "title": "Leaf Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "The Lotus salt crystal lamp impresses with its shape. The symbol means purification of conscience. The lotus is known for wisdom and knowing meaning of self-knowledge. It means a growth flower and leads to enlightenment. The lotus flower is also a symbol of warmth and passion, the lamp connects all these properties together in itself. The lamp creates a good room climate and ensures positive energy and a good atmosphere. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Lotus Salt Lamp",  
    "saleprice": "33.99 €", 
    "oldprice": "36.00 €", 
    "slug": "lotus-salt-lamp",  
    "size": "20x15 cm", 
    "weight": "3-3.5 kg", 
    "src": "assets/img/portfolio/lamps/lotus.png",   
    "title": "Lotus Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "The mushroom salt crystal lamp is made by its shape. It is a natural product. The salt lamp is free from environmental toxins. The salt crystal improves the air you breathe, creates a good room climate, it allows you to relax and feel good. Mushroom lovers! here is another customized show piece for you, to make you smile and your day bright. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Mushroom Salt Lamp",  
    "saleprice": "35.99 €", 
    "oldprice": "40.00 €", 
    "slug": "mushroom-salt-lamp",  
    "size": "20x15x10 cm", 
    "weight": "2.5-3 kg", 
    "src": "assets/img/portfolio/lamps/mushroom.png",   
    "title": "Mushroom Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "The four candles salt crystal lamp impresses with its natural shape. It gives a warm, comfortable light, creates positive energy and a good atmosphere. The lamp cleans the room air, ensures relaxation and creates well-being.", 
    "name": "Natural Salt Lamp",  
    "saleprice": "13.99 €", 
    "oldprice": "15.00 €", 
    "slug": "4 Candles salt lamp",  
    "size": "15x10 cm", 
    "weight": "2-2.5 kg", 
    "src": "assets/img/portfolio/lamps/natural-1.png",   
    "title": "Natural Salt Lamp by Himalayan Salts"  
  }, 
  { 
    "category": "lamps", 
    "desc": "The octane salt crystal lamp impresses with its shape. The lamp stands for light liquid, the room is flooded with light and yet the light is cosy and warm. The salt crystal provides positive energy, an all-round good atmosphere improves the room climate and reduces stress. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Octane Salt Lamp",  
    "saleprice": "30.99 €", 
    "oldprice": "35.00 €", 
    "slug": "octane-salt-lamp",  
    "size": "15x20 cm", 
    "weight": "2.5-3 kg", 
    "src": "assets/img/portfolio/lamps/octacone.png",   
    "title": "Octane Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "The orchid salt crystal lamp impresses with its unique shape. It stands for beauty, uniqueness, passion, love, longing and fertility. The lamp improves the indoor climate, promotes a healthy, positive atmosphere, ensures relaxation and well-being. This lamp is often bought by loving couples. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Orchid Salt Lamp",  
    "saleprice": "31.99 €", 
    "oldprice": "35.00 €", 
    "slug": "orchid-salt-lamp",  
    "size": "10x10x20 cm", 
    "weight": "2.5-3 kg", 
    "src": "assets/img/portfolio/lamps/orchid.png",   
    "title": "Orchid Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "The oval salt crystal lamp impresses with its unique shape. The lamp symbolizes a three-dimensional body and is referred to as an ovoid. The salt crystal floods the room with its unique orange color and red light into a warming oasis. The salt lamp promotes health through good indoor air, a positive, comfortable atmosphere, brings relaxation and serves to reduce stress. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Oval Salt Lamp",  
    "saleprice": "29.99 €", 
    "oldprice": "32.99 €", 
    "slug": "oval-salt-lamp",  
    "size": "15x15x20 cm", 
    "weight": "3.5-5 kg", 
    "src": "assets/img/portfolio/lamps/oval.jpg",   
    "title": "Oval Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "The Palm salt crystal lamp impresses with its unique shape. It serves as a symbol in Christianity e.g., palm Sunday and in Latin means palm. The salt natural product improves the indoor climate, creates a wonderful atmosphere, is used for relaxation and ensures well-being. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Palm Salt Lamp",  
    "saleprice": "35.99 €", 
    "oldprice": "40.00 €", 
    "slug": "palm-salt-lamp",  
    "size": "20x15x10 cm", 
    "weight": "2.5-3 kg", 
    "src": "assets/img/portfolio/lamps/palm.png",   
    "title": "Palm Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "The pyramid salt lamp Delighted by its unusual shape. The salt stone promotes a good indoor climate and creates a comfortable atmosphere. Floods the room with its warming light. Provides relaxation, stress relief and promotes well-being. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Pyramid Salt Lamp",  
    "saleprice": "30.99 €", 
    "oldprice": "35.00 €", 
    "slug": "pyramid-salt-lamp",  
    "size": "15x20 cm", 
    "weight": "2.5-3 kg", 
    "src": "assets/img/portfolio/lamps/pyramid.png",   
    "title": "Pyramid Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "The pyramid salt crystal lamp that impresses with its shape and brings everything to one point. It shines in warming light and maintains the room. The salt crystal ensures a good climate, the lamp conveys positive energy, a healthy atmosphere, is used for relaxation and promotes well-being. Includes 1 light bulb,1 m cable with socket and wooden base.", 
    "name": "Pyramid Salt Lamp",  
    "saleprice": "31.99 €", 
    "oldprice": "35.00 €", 
    "slug": "pyramid-2-salt-lamp",  
    "size": "15x20 cm", 
    "weight": "2.5-3 kg", 
    "src": "assets/img/portfolio/lamps/pyramid-2.jpg",   
    "title": "Pyramid Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": " The candle crystal salt lamp is innovatively cleaned by its shape. It decorates every table in every room, provides comfort and warmth. The salt crystal creates a good room climate and a pleasant atmosphere. The design makes it so innovative and eye catching for the customers.",     "name": "Himalayan Salt 3 candles Holder",  
    "saleprice": "9.99 €", 
    "oldprice": "12.00 €", 
    "slug": "rectangular-salt-lamp",  
    "size": " 15x6 cm", 
    "weight": "1-1.5 kg", 
    "src": "assets/img/portfolio/lamps/rectanular-1.png",   
    "title": "Rectangular Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "The salt crystal candle lamp is also ideal as a candlelight dinner. Candlelight is a romantic light; it creates a relaxing positive atmosphere. The salt crystal promotes a healthy room climate and creates a feel-good atmosphere.", 
    "name": " Himalayan Salt 4 candles Holder ",  
    "saleprice": "19.99 €", 
    "oldprice": "22.00 €", 
    "slug": "rectangular-2-salt-lamp",  
    "size": "18x6 cm", 
    "weight": "1.5-2 kg", 
    "src": "assets/img/portfolio/lamps/rectanular-2.png",   
    "title": "Rectangular Salt Lamp by Himalayan Salts" 
  
 
}, 
  { 
    "category": "lamps", 
    "desc": "The salt crystal candle lamp is innovative because of its shape. Candlelight is a romantic light, it is made for a relaxing and positive situation.", 
    "name": " Himalayan Salt 2 candles Holder ",  
    "saleprice": "8.99 €", 
    "oldprice": "11.00 €", 
    "slug": "rectangular-3-salt-lamp",  
    "size": "10x6 cm ", 
    "weight": "1 kg", 
    "src": "assets/img/portfolio/lamps/rectanular-3.png",   
    "title": "Rectangular Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "The salt crystal candle lamp is also ideal as a candlelight dinner. Candlelight is a romantic light; it creates a relaxing positive atmosphere. The salt crystal promotes a healthy room climate and creates a feel-good atmosphere", 
    "name": " Himalayan Salt 5 candles Holder ",  
    "saleprice": "22.50 €", 
    "oldprice": "25.00 €", 
    "slug": "rectangular-4-salt-lamp",  
    "size": "20x6 cm", 
    "weight": "2-2.5 kg", 
    "src": "assets/img/portfolio/lamps/rectanular-4.png",   
    "title": "Rectangular Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "lamps", 
    "desc": "The salt crystal candle lamp impresses with its shape. The candle lamp floods the room with its warming light, creates a cosy atmosphere, good mood and good vibration. The salt crystal ensures a healthy climate and relaxation.", 
    "name": "Round candle holder",  
    "saleprice": "4.89 €", 
    "oldprice": "5.00 €", 
    "slug": "round-salt-lamp",  
    "size": "8-10 cm", 
    "weight": "1 kg", 
    "src": "assets/img/portfolio/lamps/round.png",   
    "title": "Round Salt Lamp by Himalayan Salts" 
  }, 
  { 
    "category": "tiles", 
    "desc": "The round salt crystal block is versatile. The salt stone is a great natural salt block without pollutants and environmental toxins. It is extracted from the deep Himalayan salt mine. The block is a champion for the kitchen. The salt plate could be freezed as well. As well as serving for cold dishes, e.g. For sausage, vegetables, cheese, salad, fish, etc. What is the top of all things you can use it as a grill at exreme warm temperatures. Also, a gourmet stone. Visually and its design is overwhelming. It is attractive in terms of health and creates a good indoor climate.", 
    "name": "Circular Salt Block",  
    "oldprice": "€24.99", 
    "saleprice": "€27.00", 
    "slug": "circular-salt-block",  
    "size": " 20x20x4 cm", 
    "weight": "3-3.5 kg", 
 
    "src": "assets/img/portfolio/tiles/circle-block.jpg",   
    "title": "Circular Salt Block by Himalayan Salts" 
  }, 
  { 
    "category": "tiles", 
    "desc": "The Rectangular Salt Crystal Plate is a good therapist in your home and has a low hourly wage. The salt crystal plate is known for its versatility. A rectangular Himalayan salt made from a plate of natural solid rock salt is a master in its field. It fits well in any room and adds value to the interior of your home. It is an optical master in the shiny rooms and is characterized by its beautiful warm light. The indoor air is great and lets you breathe easily. It drives away unpleasant smells and makes you feel relax in the good atmosphere.", 
    "name": "Rectangular Salt Brick",  
    "oldprice": "€7.99", 
    "saleprice": "€10.00", 
    "slug": "rectangular-salt-brick", 
    "size": " 20x10x2.5 cm", 
    "weight": "1-1.5 kg",  
    "src": "assets/img/portfolio/tiles/rect_brick.jpg",   
    "title": "Rectangular Salt Brick by Himalayan Salts" 
  }, 
  { 
    "category": "tiles", 
    "desc": "The rectangular salt crystal plate is known for its versatility. A rectangular Himalayan salt made from a plate of natural solid rock salt is a master in its field. It fits well in the kitchen and as well adds the value to the interiors of your house. It is an optical master in the shiny rooms and stands out with its beautiful warm light. The indoor air is great and lets you breathe well. It drives away unpleasant smells and relaxes with the good atmosphere. The salt plate in the kitchen is a small rubber, it gives off a slight salt content ideal for all dishes. The rectangular salt platter is a necessary addition to every kitchen, as it can be used in many ways, be it for searing meat or for refrigerating food",  
    "name": "Salt Crystal Plate",  
    "oldprice": "€24.00", 
    "saleprice": "€18.50", 
    "slug": "rectangular-salt-plate", 
    "size": "20x20x2.5 cm", 
    "weight": "kg", 
   
    "src": "assets/img/portfolio/tiles/rect-plate.jpg",   
    "title": "Rectangular Salt Plate by Himalayan Salts" 
  }, 
  { 
    "category": "tiles", 
    "desc": "The round salt crystal panel is a good interior designer in your home. The quality of your house is of great importance. There are no limits to individuality, which makes the flare of your house impressive. The small round salt stone promotes health, creates a good indoor climate, a positive atmosphere and invites you to relax.", 
    "name": "Circular Salt Tile",  
    "oldprice": "€20.99", 
    "saleprice": "€25.00", 
    "slug": "circular-salt-tile",  
    "size": " 20x20x4 cm", 
    "weight": "3-3.5 kg", 
 
    "src": "assets/img/portfolio/tiles/circle-2.png",   
    "title": "Circular Salt Tile by Himalayan Salts" 
  }, 
  { 
    "category": "lick", 
    "desc": "The Himalayan salt lick stone is used in agriculture and precisely covers the mineral requirements of an animal. An animal cannot live without mineral intake. Despite the daily feed, you should make sure that optimal performance and a resilient physical condition are guaranteed. So that there are no deficiency symptoms. Among other things, sodium maintains the osmotic pressure in the cells, it regulates the water balance and plays an important role in the transmission of impulses in nerve tissue and muscle fibers. Magnesium is important for muscle, nerve function and bone building. Calcium is an essential component for the transmission of nerve impulses and is required for building bones for blood clotting, it plays an important role. Magnesium is required for mineral and fat metabolism. Zinc is an essential component of numerous proteins which an intact immune system requires. Iodine is essential for thyroid function and metabolism. Copper plays an important role in the formation of nerves, blood, connective tissue and bones. Selenium is a component of many proteins, it is important for antioxidant processes and the iodine metabolism, it is a so-called radical scavenger, irreplaceable for the animal organism.", 
    "name": "Animal Lick Salt",  
    "oldprice": "€3.50/kg", 
    "saleprice": "€1.90/kg", 
    "slug": "animal-lick-salt", 
    "size": " cm", 
    "weight": "kg", 
  
    "src": "assets/img/portfolio/lick/lick-1.png",   
    "title": "Animal Lick Salt by Himalayan Salts" 
  }, 
  { 
    "category": "lick", 
    "desc": "The Himalayan salt lick stone is used in agriculture and precisely covers the mineral requirements of an animal. An animal cannot live without mineral intake. Despite the daily feed, you should make sure that optimal performance and a resilient physical condition are guaranteed. So that there are no deficiency symptoms. Among other things, sodium maintains the osmotic pressure in the cells, it regulates the water balance and plays an important role in the transmission of impulses in nerve tissue and muscle fibers. Magnesium is important for muscle, nerve function and bone building. Calcium is an essential component for the transmission of nerve impulses and is required for building bones for blood clotting, it plays an important role. Magnesium is required for mineral and fat metabolism. Zinc is an essential component of numerous proteins which an intact immune system requires. Iodine is essential for thyroid function and metabolism. Copper plays an important role in the formation of nerves, blood, connective tissue and bones. Selenium is a component of many proteins, it is important for antioxidant processes and the iodine metabolism, it is a so-called radical scavenger, irreplaceable for the animal organism", 
    "name": "Animal Lick Salt",  
    "oldprice": "€3.50/kg", 
    "saleprice": "€1.90/kg", 
    "slug": "animal-2-lick-salt",  
    "src": "assets/img/portfolio/lick/lick-2.png",   
    "title": "Animal Lick Salt by Himalayan Salts" 
  }, 
  { 
    "category": "lick", 
    "desc": "The Himalayan salt lick stone is used in agriculture and precisely covers the mineral requirements of an animal. An animal cannot live without mineral intake. Despite the daily feed, you should make sure that optimal performance and a resilient physical condition are guaranteed. So that there are no deficiency symptoms. Among other things, sodium maintains the osmotic pressure in the cells, it regulates the water balance and plays an important role in the transmission of impulses in nerve tissue and muscle fibers. Magnesium is important for muscle, nerve function and bone building. Calcium is an essential component for the transmission of nerve impulses and is required for building bones for blood clotting, it plays an important role. Magnesium is required for mineral and fat metabolism. Zinc is an essential component of numerous proteins which an intact immune system requires. Iodine is essential for thyroid function and metabolism. Copper plays an important role in the formation of nerves, blood, connective tissue and bones. Selenium is a component of many proteins, it is important for antioxidant processes and the iodine metabolism, it is a so-called radical scavenger, irreplaceable for the animal organism", 
    "name": "Salt Lick Lump",  
    "oldprice": "€5.00/kg", 
    "saleprice": "€3.50/kg", 
    "slug": "salt-lick-lumps",  
    "src": "assets/img/portfolio/lick/lick-lumps.png",   
    "title": "Salt Lick Lump by Himalayan Salts" 

  }]